### ISSUE TITLE
[Feature Update] Navbar

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#1]
1. update navbar with features like hovering effects .

2. make the nav links align right .

3. make navbar Responsive.

All the features are to be added in one PR.

if You want to work on the Issue pls do reply and I will assign you the same.

Happy Contributing Hactoberfest'23🤗

**Comment by ani-netizen** [comment]
Hey @abhay-raj19 

I can help you with this kindly assign it to me

**Comment by AnushkaPhogat16** [comment]
Hey! I'd like to work on this issue, please assign it to me. Thanks!

**Comment by abhay-raj19** [comment]
Hey @ani-netizen work on it ASAP  and raise the PR's.

**Comment by Adityakr55** [comment]
can you please assign me this issue
