### ISSUE TITLE
Backend Setup + Registration/Login Functionality

### ISSUE THREAD

**Issue by aayushwrld** [abhay-raj19/FitBody#101]
Issue
-

- There is no registration/login functionality currently. The register/login button do not work.
- There is no backend.

Resolution
-
Adding functionality for users to register and login onto the website.
I will properly discuss the schema required with you so that there is no hinderance when more features are needed to be added.

The project currently does not have a backend server and a connect DB. So, I will setup both the things and make them ready to be connect with the frontend part of this project. I will also deploy the server to make it production ready.
Other than the basic setup, I will also develop the complete login/signup functionality (backend). It will include all necessary things like schema(s), validation files + middlewares, error handling, JWTs, profile customization, etc.

Tech libraries/frameworks which I will use to accomplish the above mentioned task(s):
-
- ExpressJS
- NodeJS
- JWT
- MongoDB
- Mongoose
- Cookies

**Comment by aayushwrld** [comment]
Hey @abhay-raj19! Can you assign me this issue so I can work on it?

**Comment by rawani123** [comment]
can you assign this issue to me also so i can work on it? 
I am also a contributor from GSSOC'24

**Comment by InshiyaRavat** [comment]
can you assign it to me too
contributor at GSSOC'24

**Comment by abhay-raj19** [comment]
that looks like too good issue up till now , and would be great if you initilise the PostgreSQL(can be neontech,avien) with prisma if possible .
you can work on it and will look to the PR.

**Comment by aayushwrld** [comment]
> that looks like too good issue up till now , and would be great if you initilise the PostgreSQL(can be neontech,avien) with prisma if possible . you can work on it and will look to the PR.

I currently only know MongoDB. If that's fine I can initialise with that?

**Comment by aayushwrld** [comment]
@abhay-raj19 May I do it with MongoDB?
