### ISSUE TITLE
Add automatic contributor profile add to readme.

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#104]

**Comment by SumitKumar-17** [comment]
@abhay-raj19 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by abhay-raj19** [comment]
Sure , How will u do this can you share the overview ?

**Comment by SumitKumar-17** [comment]
yes Sure.
1)First, I will create a YAML file inside the .github/workflows directory in  the  repository. I will name it  like update-contributors.yml.
2)define the workflow including triggers, actions, and steps.
3)Install Required Dependencies
4)Write the yml file 
5)update the readme with the commands

**Comment by abhay-raj19** [comment]
Seems bit confusing! to me, but proceed anyway will look to PR and Test it out locally them merge.
