### ISSUE TITLE
Make up darkmode compatible 

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#105]
![image](https://github.com/abhay-raj19/FitBody/assets/96302417/34297550-d342-4f78-b151-bb797fae650d)

make this image dark mode compatible and also inhance its UI design for this specific images.

**Comment by Vedantjn** [comment]
I can resolve this.

**Comment by SumitKumar-17** [comment]
@abhay-raj19 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by dhruv389** [comment]
please assign me this issue . i have idea that how to improve this section in night mode .
and i have already completed my previous issue successfully . 

After Changes it looks like this :
---

![Screenshot 2024-05-11 014008](https://github.com/abhay-raj19/FitBody/assets/117587892/cfdc59f5-f910-4534-8260-69db150d5302)

**Comment by abhay-raj19** [comment]
LooKs fine make it bit more attractive and make "Personal trainer" font looks better in dark mode .
good to go @dhruv389
