### ISSUE TITLE
Authentication for the Project

### ISSUE THREAD

**Issue by Ashutowsh** [abhay-raj19/FitBody#106]
Hey @abhay-raj19, I have gone through the website and found that the authentication functionalities are yet to be done.

Functionalities

1. Login/ Logout
2. Adding users according to the plan they have chosen.
3. Special Login for users and admins
4. Forgot Password/Reset Password

I can handle both the frontend as well as backend parts for these functionalities.

Tech Stack -
1. MongoDb - For Storing Users Info
2. Express.js
3. Node.js
4. JWT - JSON Web Tokens

So, as a **GSSC'24** participant, I want to be a part of this project and contribute to the same. 
Can you please assign me this issue? Also, label this issue accordingly.

**Comment by divyanshahlawat** [comment]
can u issue this task to me?

**Comment by abhay-raj19** [comment]
Looks good , now you can proceed @Ashutowsh !!

**Comment by Ashutowsh** [comment]
Thanks @abhay-raj19 for giving me this opportunity. I will complete my tasks as soon as possible under GSSC'24.
Can you assign an appropriate level to this issue?  It would be a great help. Thank You!
