### ISSUE TITLE
To Add a Login through Google page to make it easy for users to access instead of old login through username and password 

### ISSUE THREAD

**Issue by Evadshell** [abhay-raj19/FitBody#108]
Description:
I propose enhancing the login functionality of the FitBody project by implementing Passport.js for authentication and integrating OAuth2 Google sign-in. This will improve security, usability, and convenience for users.

Proposed Changes:

Integrate Passport.js for authentication.
Implement OAuth2 Google sign-in.
Update the login page UI to accommodate the new authentication methods.
Provide documentation for developers on how to set up and configure the new authentication system.

Expected Benefits:

Enhanced security through standardized authentication mechanisms provided by Passport.js.
Improved user experience with the option for OAuth2 Google sign-in, reducing friction for new users.
Potential for increased user engagement and retention.

References:

Passport.js Documentation
OAuth2 Google Sign-In Documentation

Additional Information:

I have previously implemented similar authentication features on my personal website ((https://secrets-phi.vercel.app/)), showcasing my experience with Passport.js and OAuth2 Google sign-in. I'm excited to contribute these skills to FoodiesWeb and enhance its authentication system.I assure you that while enhancing the login page, I'll ensure the backend logic remains consistent and functional. I'm excited to contribute these skills to Fitbody and enhance its authentication system.

**Comment by Evadshell** [comment]
Please assign this issue to me

**Comment by abhay-raj19** [comment]
Looks good @Evadshell , proceed with it !!
