### ISSUE TITLE
Create Login and Registration pages

### ISSUE THREAD

**Issue by Niharika0104** [abhay-raj19/FitBody#111]
#### Tasks:
1. **Design Login Page UI:** Design the user interface for the login page, including input fields for email/username and password, as well as options for password recovery and registration.
   - **Steps to Implement:**
     1. Define the layout and styling of the login form elements.
     2. Incorporate design elements for password recovery and registration links/buttons.
   - **Expected Outcome:** Users should see a visually appealing login page with intuitive input fields and options for password recovery and registration.

2. **Develop Login Page Functionality:** Implement frontend and backend logic for user authentication on the login page.
   - **Steps to Implement:**
     1. Create React components or templates for the login page.
     2. Implement frontend validation for email/username and password fields.
     3. Integrate with backend API endpoints to handle user authentication requests.
   - **Expected Outcome:** Users should be able to log in successfully using valid credentials, with appropriate error messages displayed for invalid login attempts.

3. **Design Registration Page UI:** Design the user interface for the registration page, including input fields for username, email, password, and confirm password.
   - **Steps to Implement:**
     1. Define the layout and styling of the registration form elements.
     2. Incorporate design elements for password strength indicator and terms of service agreement.
   - **Expected Outcome:** Users should see a visually appealing registration page with intuitive input fields and options for password strength indication and terms acceptance.

4. **Develop Registration Page Functionality:** Implement frontend and backend logic for user registration on the registration page.
   - **Steps to Implement:**
     1. Create React components or templates for the registration page.
     2. Implement frontend validation for username, email, password, and confirm password fields.
     3. Integrate with backend API endpoints to handle user registration requests.
   - **Expected Outcome:** Users should be able to register successfully with valid credentials, with appropriate error messages displayed for invalid registration attempts.

**Comment by anandromy** [comment]
Hey niharika can I take on this issue?

**Comment by abhay-raj19** [comment]
That's also looks good @Niharika0104 ,proceed .

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
