### ISSUE TITLE
Implement Contact Form Validation with React Toastify

### ISSUE THREAD

**Issue by Niharika0104** [abhay-raj19/FitBody#112]
#### Description:
Enhance the user experience on the contact page by implementing form validation using React Toastify. This will provide users with real-time feedback on their input and improve the overall usability of the contact form.

#### Tasks:
1. **Integrate React Toastify:** Install and configure React Toastify library in the project to display toast notifications for form validation messages.
   - **Steps to Implement:**
     1. Install React Toastify package using npm or yarn.
     2. Configure React Toastify to display notifications at appropriate positions on the screen.
   - **Expected Outcome:** React Toastify should be successfully integrated into the project, ready to display form validation messages.

2. **Frontend Form Validation:** Implement frontend form validation logic to check the validity of input fields in the contact form and display corresponding toast notifications using React Toastify.
   - **Steps to Implement:**
     1. Write JavaScript/React code to validate user input in the contact form fields.
     2. Utilize React Toastify to display toast notifications for validation errors such as empty fields, invalid email format, or message length.
   - **Expected Outcome:** Users should receive immediate feedback via toast notifications when they enter invalid data in the contact form.

**Comment by dhruv8433** [comment]
@abhay-raj19 i would like to work on this issue and i have good knowlege of react toastify can you please assign it to me..?

**Comment by abhay-raj19** [comment]
@Niharika0104  Looks Good , now you can proceed with it .

**Comment by Manaswini123456** [comment]
Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue so that I can provide my insights and solutions.
