### ISSUE TITLE
Security bug : ZOD Authentication in registration of the User 

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [abhay-raj19/FitBody#115]
**@abhay-raj19** I have not seen any Zod Authentication in this project in backend. 

As a Good Authenticated Site. There Should be Zod Authentication on website , So then the user  can't add wrong **type** of username and passwords while registring to the database 

More  about  Zod  -> https://zod.dev/

![image](https://github.com/abhay-raj19/FitBody/assets/122930278/51891f7d-3b9d-49b8-ba27-34a927dfcd63)

**Comment by ujjwalagrawal-1** [comment]
**@abhay-raj19** I want to contribute to this Project as I know all about Zod Authentication on the site.

Please Assign me this issue.

**Comment by KartikeySingh05** [comment]
I am interested in solving this issue please assign this issue to me under GSSOC'24

**Comment by abhay-raj19** [comment]
Good to go @ujjwalagrawal-1 implement Zod validations just make sure that all those schemas you should make inside the seprate folder and import them in validation files.

**Comment by ujjwalagrawal-1** [comment]
Sure @abhay-raj19  Thanks for Assigining me
