### ISSUE TITLE
Enchancing Contact Us section

### ISSUE THREAD

**Issue by AlaynaShaheen** [abhay-raj19/FitBody#117]
Contact Us UI can be made better and more visually appealing. Also there is lot of white space around which isn't looking good. 
 
![Screenshot 2024-05-11 133847](https://github.com/abhay-raj19/FitBody/assets/111679498/65f2ec7e-301f-4053-86c9-774645f53a95)
![Screenshot 2024-05-11 133902](https://github.com/abhay-raj19/FitBody/assets/111679498/72be63d3-3073-4639-a1a8-bbfe2270c559)

I am a contributor under GSSoC'24 and I have a good experience in development. I can resolve this issue. Please assign this to me.

**Comment by abhay-raj19** [comment]
// duplicate issue ( issue exists)
