### ISSUE TITLE
Dark Mode not applied in Footer

### ISSUE THREAD

**Issue by Chetan8299** [abhay-raj19/FitBody#119]
The Dark mode is not applied in the footer as you can see from the image below
![image](https://github.com/abhay-raj19/FitBody/assets/167693543/47f4438d-28bb-48c9-acc7-b43ba902c392)

Also the Dark mode is not retained after the refresh it switches back to light mode.

Please assign this issue to me under GSSOC'24 as it could be my first PR.

**Comment by abhay-raj19** [comment]
Good to go @Chetan8299 just see that is this issue not made prior to you .
