### ISSUE TITLE
Content writer for the full website.

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#12]
Want to change up all my content from `Lorem ipsum ` to the content that perfectly fits into the place for the component.

and ,

alignment of the fitbody logo in nav and footer .

![image](https://github.com/abhay-raj19/FitBody/assets/96302417/59645141-bf6b-4895-9ea8-dd89ab15499d)

there is the mis-alignment with the logo of the Dumble.

1. You can totally change up the logo and add a perfect logo for the gym website -related logo , so that it matches the alignment .

2. Or else make the same Dumble logo perfectly align with  **FITBODY** text.

**Comment by akssshh** [comment]
Can i work on this issue @abhay-raj19

**Comment by ASIMNEUPANE** [comment]
okay i will do it

**Comment by abhay-raj19** [comment]
@akssshh You can go for it and raise the PR's with the changes ASAP.

**Comment by akssshh** [comment]
Okay Thanks @abhay-raj19

**Comment by ASIMNEUPANE** [comment]
i have already done that bro checkout your pr

**Comment by abhay-raj19** [comment]
@ASIMNEUPANE Pls from next time onwards do not raise PR before assigning it to you , Pls give Chance to everyone.
 From next time onwards be careful.

**Comment by ASIMNEUPANE** [comment]
i have done that please check your pr

**Comment by abhay-raj19** [comment]
Hey, @akssshh sorry for the inconvenience pls take up another issue or open up a new issue .
So, sorry for the inconvenience 😓.

**Comment by akssshh** [comment]
> Hey, @akssshh sorry for the inconvenience pls take up another issue or open up a new issue . So, sorry for the inconvenience 😓.

No problem at all! @abhay-raj19
