### ISSUE TITLE
contact UI

### ISSUE THREAD

**Issue by dhruv8433** [abhay-raj19/FitBody#121]
contack form look like a not good and also not matched with fit_body web 
![image](https://github.com/abhay-raj19/FitBody/assets/114583978/dca0c3fe-e353-437d-b267-00e2fba36a5a)

i make a good look for you with fucntionality, toastify and validation. 
like this 
![image](https://github.com/abhay-raj19/FitBody/assets/114583978/f279205c-65ea-4513-9b62-4e21e84dc006)

**Comment by abhay-raj19** [comment]
Good to go @dhruv8433 .

**Comment by abhay-raj19** [comment]
just make the image bit more similar to gym guy or some other gym related thing.

**Comment by dhruv8433** [comment]
ok got it
Thank you @abhay-raj19

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .

**Comment by dhruv8433** [comment]
@abhay-raj19 please close this issue and add level tag in this
