### ISSUE TITLE
user controllers - backend

### ISSUE THREAD

**Issue by ayann07** [abhay-raj19/FitBody#123]
I would like to add backend for register, signup ,change password controllers.

**Comment by ayann07** [comment]
please assign me under gssoc'24

**Comment by abhay-raj19** [comment]
Backend is been initisilised inside the Server Folder so refer to it .

**Comment by ayann07** [comment]
Only register feature is there in usercontroller, I would add login using jwt authentication and forget password features aswell.

**Comment by ayann07** [comment]
I have seen that but still there is no login and forget password features in it, so I will write controllers for that .

**Comment by abhay-raj19** [comment]
Proceed @ayann07
