### ISSUE TITLE
Contact section link at the footer

### ISSUE THREAD

**Issue by kaizentechcult** [abhay-raj19/FitBody#124]
![image](https://github.com/abhay-raj19/FitBody/assets/169530449/88833e91-83f4-4540-afad-1f1007250f51)

When we click on this contact me(located in footer), we dont go to the contact me section but instead at the top. 
i can fix that (i have already fixed that)
Under gssoc'24 please assign this issue to me with the appropriate level. 

I will raise the pr right when assigned

**Comment by abhay-raj19** [comment]
Good to Go @kaizentechcult

**Comment by krishkh** [comment]
@abhay-raj19 actually... im sorry but i raised the issue from the wrong account, that account is for my college club. I messed up can you assign that issue to this account i can send you a screenshot to confirm that is my account
![image](https://github.com/abhay-raj19/FitBody/assets/51072063/3a305f66-4dd0-447c-9cde-7f7c8b195587)
