### ISSUE TITLE
Regarding Styling and fixing

### ISSUE THREAD

**Issue by Dynamic-Aryan** [abhay-raj19/FitBody#125]
In this i can fix footer import's as path's are not assign their,, also here in the hero section ,,i can add one extra image ,,that is 2 images will be present their ,,on every reload that image will change,, and also many things i can do ,,
Under Gssoc'24 ,,please assign me this task ,,I amable to do it 😊

Thank You @abhay-raj19

**Comment by abhay-raj19** [comment]
Good to go @Dynamic-Aryan
Just make sure the on change UI does't Hampers

**Comment by Dynamic-Aryan** [comment]
I added some changes in hero section ,,that on just refreshing ,,the hero image will be change ,,please make a look at it ,,this was my 1st step towards contribution here

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
