### ISSUE TITLE
GSSOC 24 | Adding new page for workouts

### ISSUE THREAD

**Issue by satyam8932** [abhay-raj19/FitBody#126]
Hey man, I would like to add a page where users can see the workouts according to their level like beginner, intermediate and advanced with videos.

I'm a gym guy and developer as well, so it would be pretty straightforward for me.

Let me know if you want to know more about my approach or something else.
Please assign me this issue.
Thanks

**Comment by abhay-raj19** [comment]
Good to go @satyam8932 but make it sure that the UI for the new component matches with the FitBody UI.

**Comment by satyam8932** [comment]
ofcourse bro

let me show you my work
here is my Upwork profile
https://www.upwork.com/freelancers/~0140b941ccaa0e490d

**Comment by satyam8932** [comment]
bro please also add level of this issue 

Thanks
Satyam

**Comment by satyam8932** [comment]
Hey Boss, I have completed the changes and made a pull request which passed
all the checks so can you please merge the PR and also for the issue.

PR - https://github.com/abhay-raj19/FitBody/pull/137
ISSUE - https://github.com/abhay-raj19/FitBody/issues/126

Thanks :)
Satyam

**Comment by satyam8932** [comment]
Hey can you please approve it

**Comment by satyam8932** [comment]
New Issue - https://github.com/abhay-raj19/FitBody/issues/180
NEW PR - https://github.com/abhay-raj19/FitBody/pull/179
Old Issue - https://github.com/abhay-raj19/FitBody/issues/126


Hi bro, The previous PR was having problem with conflicts so i created a
new PR and Issues please merge them and add the new issue in new PR.

This time everything is perfect

Thanks

**Comment by satyam8932** [comment]
Successfuly merged the PR https://github.com/abhay-raj19/FitBody/pull/179
