### ISSUE TITLE
Feature: Implementing stripe for payments 

### ISSUE THREAD

**Issue by Adeesh-bode** [abhay-raj19/FitBody#132]
The issue involves implementing Stripe as a payment processing solution for a web application. This feature aims to enable secure and efficient online transactions for users, supporting various payment methods such as credit cards, bank transfers, and more. The task would include integrating the Stripe API into the application, setting up the necessary backend services for handling payments, and designing a user-friendly payment interface. Additionally, ensuring compliance with financial regulations and data security standards will be crucial to successfully implementing Stripe.

**Comment by abhay-raj19** [comment]
Go for it @Adeesh-bode

**Comment by Adeesh-bode** [comment]
review my earlier pr..so as I can work on other issue I got assigned for fitbody
