### ISSUE TITLE
Price model

### ISSUE THREAD

**Issue by ayann07** [abhay-raj19/FitBody#138]
For joining the gym, we will be requiring prices for different categories such as premium member, regular member etc. So I'll write backend for that

My implementation would be-

Pricing Category Model:
Fields- 
Plan name
Price 
Description 

Controllers:

 Pricing Category Controller:
   - Functions:
     - Create pricing category: Add a new pricing category to the database
     - Get all pricing categories: Retrieve a list of all pricing categories
     - Get pricing category by ID: Retrieve details of a specific pricing category
     - Update pricing category: Modify details of an existing pricing category
     - Delete pricing category: Remove a pricing category from the database

I would be working under GSSOC'24.

**Comment by abhay-raj19** [comment]
Go for it @ayann07
