### ISSUE TITLE
 Add Reviews Section to FitBody

### ISSUE THREAD

**Issue by dhruv8433** [abhay-raj19/FitBody#140]
@abhay-raj19 
Create a new section on the website dedicated to customer reviews.

something like this ui:
![image](https://github.com/abhay-raj19/FitBody/assets/114583978/43af9f0b-d0d6-4470-839f-7b0e8d7bc960)

this will help to build better user-experience

**Comment by abhay-raj19** [comment]
Go for that Build !!
Nice idea 
Do join the Discord Community as we want some new ideas like this there come on 👍

**Comment by dhruv8433** [comment]
sure and thank you @abhay-raj19

**Comment by dhruv8433** [comment]
@abhay-raj19 please close this issue and add level tag in this
