### ISSUE TITLE
About Us Section

### ISSUE THREAD

**Issue by Hemashree21** [abhay-raj19/FitBody#142]
In the quick links section, the about us link is present but there is no separate page highlighting the importance of the app. @abhay-raj19 please assign this issue to me so that I can fix it.

![image](https://github.com/abhay-raj19/FitBody/assets/138188163/69009905-20cd-418f-ab14-b60d21bd49b1)

**Comment by SanaAzeem512** [comment]
please assign this issue to me

**Comment by abhay-raj19** [comment]
Good to go @SanaAzeem512 .

**Comment by Hemashree21** [comment]
@abhay-raj19 Can you please add level 1/level 2/level 3 label to this issue?

**Comment by Hemashree21** [comment]
@Ayushhgupta39 my commit (About Us) is no longer in the branch, are there any changes required?

**Comment by Ayushhgupta39** [comment]
@abhay-raj19 Can you check this

**Comment by Hemashree21** [comment]
@abhay-raj19 did you check this?
