### ISSUE TITLE
missing animation in Testimonials section

### ISSUE THREAD

**Issue by dev04sa** [abhay-raj19/FitBody#146]
@abhay-raj19  , as you can see . In Testimonials section animation is missing I want to add this.
kindly assign this issue to me.

![Screenshot 2024-05-12 121115](https://github.com/abhay-raj19/FitBody/assets/129666293/40ee7a74-a24c-4bf2-8281-860030a295bb)

https://github.com/abhay-raj19/FitBody/assets/129666293/5e1a0475-76f0-4a77-9a0b-acd6a4c76fa0

**Comment by abhay-raj19** [comment]
Go for it , i will see to it as without animation also it is looking fine though but if you have some eye catchy idea though you can proceed brother.
