### ISSUE TITLE
improve contact us form with client side validation

### ISSUE THREAD

**Issue by Harshitazz** [abhay-raj19/FitBody#148]
![Screenshot 2024-05-12 130937](https://github.com/abhay-raj19/FitBody/assets/118474653/ccea7c21-da87-4f14-9542-a55c0af338c4)
setting margins and style

**Comment by abhay-raj19** [comment]
GO for it @Harshitazz

**Comment by ShreyashKathade** [comment]
I am Interested to work on this issue. Can you assign me under gssoc'24
