### ISSUE TITLE
Adding register page

### ISSUE THREAD

**Issue by Harshitazz** [abhay-raj19/FitBody#149]
adding registration form with email, setting password

**Comment by bikashsahh** [comment]
hi there! will like to resolve this issue. Kindly assign this to me.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by abhay-raj19** [comment]
go for it @Harshitazz

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhishekraoas** [comment]
Hi, I am a Full Stack Developer and I want to contribute to this issue under GSSOC'24. I can design a modern sign-up page. Please assign me.
