### ISSUE TITLE
Adding up a similar module for the testimonials .

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#15]
Add 2 testimonials section adjacent to each other .
 
 **Currently** =>

<img width="707" alt="image" src="https://github.com/abhay-raj19/FitBody/assets/96302417/c64b85bc-6fd1-4027-ba69-06521021ef43">
 
having only one testimonial section in the center for women

add the similar testimonial section for the men's also and align both of these adjacent to each other .
**Left side** for womens
**right side** for mens

**Comment by Faisalhs51** [comment]
@abhay-raj19 assign this to me

**Comment by Faisalhs51** [comment]
@abhay-raj19 please check the PR.
If any changes needed please let me know.
