### ISSUE TITLE
[BUG] : nav elements gets distorted on squeezing the screen size

### ISSUE THREAD

**Issue by Sudhanshu2306** [abhay-raj19/FitBody#151]
on a smaller screen size the nav elements moves towards bottom rather staying at the center.

![image](https://github.com/abhay-raj19/FitBody/assets/126086429/6ee8a50a-9ca7-4df2-82e2-be8439b1d66f)

**Comment by Sudhanshu2306** [comment]
Please add the GSSoC label and assign me this issue, a simple change in CSS in media queries section of nav will sort this out. Thank You!

**Comment by abhay-raj19** [comment]
Go for it @Sudhanshu2306
