### ISSUE TITLE
[BUG] : Small Screen Footer is not aligned, left margin need even-ness

### ISSUE THREAD

**Issue by Sudhanshu2306** [abhay-raj19/FitBody#152]
on squeezing the screen size footer also a lot attached to left side, adding margin or padding on left would make it look more appealing.

![image](https://github.com/abhay-raj19/FitBody/assets/126086429/2e5fbe76-ac60-46a2-8a1c-5a805fadcc0c)

**Comment by abhay-raj19** [comment]
@Sudhanshu2306 Proceed

**Comment by Sudhanshu2306** [comment]
I see this is already resolved, and currently the footer looks fantastic, so no need for the issue. Thank you!
