### ISSUE TITLE
Adding a chat bot

### ISSUE THREAD

**Issue by nagamukesh** [abhay-raj19/FitBody#153]
Adding a chatbot may help the user understand and interact with the website easily
user can ask any fitness-related doubts or website-related queries to the chatbot
please assign me this issue
I can assign it real quick

**Comment by 07-Atharv** [comment]
I'll be taking ownership of this issue to implement the chat bot integration for our gym website. I'll proceed with researching suitable chat bot platforms, designing conversation flows, integrating the chat bot into the website, training it, and ensuring smooth deployment and monitoring. Excited to contribute to enhancing the user experience!

**Comment by abhay-raj19** [comment]
Go for it just migrate the chatbot logic to some directory's not put the whole code base in one file and in main component do imports and exports heavily
