### ISSUE TITLE
Create a contact us form.

### ISSUE THREAD

**Issue by VishalGaurav01** [abhay-raj19/FitBody#154]
A contact form design that matches the Toggle theme and is responsive.
![image](https://github.com/abhay-raj19/FitBody/assets/97465452/3d7730fb-84ac-4591-8045-ff6549a29e2d)
Assignee: Please assignee this issue to me i am looking to make impactful contribution to the website.

**Comment by SanaAzeem512** [comment]
please assign this issue to me

**Comment by abhay-raj19** [comment]
without any company information , call us , and address fields it would be fine just the form and a good UI to the next of it (image).

**Comment by abhay-raj19** [comment]
but what i think so is it is duplicate , check the issue one again before working on it if so pls close this one

**Comment by VishalGaurav01** [comment]
ok @abhay-raj19, I have gone through the issues and pull requests. No successful pull requests have been made... That why going to work on this page.
