### ISSUE TITLE
Changing the images in Testimonials

### ISSUE THREAD

**Issue by dhairyagothi** [abhay-raj19/FitBody#161]
@abhay-raj19 i can change the images in testimonials please assign the issue to me 
Gssoc'24

**Comment by abhay-raj19** [comment]
make all the images diffrent as some of them are repeating and only put 4 images in women and 4 In men section that will be all fine .

**Comment by dhairyagothi** [comment]
okay fine i will do that

**Comment by dhairyagothi** [comment]
i have created a PR #187 please check it and tell me if anything extra is required

**Comment by dhairyagothi** [comment]
have you checked 
please accept PR

**Comment by dhairyagothi** [comment]
Testinomial images changed #225 
@abhay-raj19 please check tthis PR

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
