### ISSUE TITLE
I want to work on the community backend

### ISSUE THREAD

**Issue by Phinix-BI** [abhay-raj19/FitBody#166]
@abhay-raj19  hey, i want to implement a community messaging backend where the gym community members can share their messages. can you assign me this?

**Comment by abhay-raj19** [comment]
Proceed @Phinix-BI 
Do join the discord community for further changes listed

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
