### ISSUE TITLE
want to add a Contact Us from and implement the faciality to automatically sent message to the owner's email when the user is submitted the message

### ISSUE THREAD

**Issue by AnitSarkar123** [abhay-raj19/FitBody#167]
Is your feature request related to a problem? Please describe.
I'm always frustrated when anything not working or wrong info given in the app and the contact options is not given

Describe the solution you'd like
i am using email.js

please assign me under GSSoc'24

**Comment by bikashsahh** [comment]
Hi there! ,will like to resolve this issue kindly assign me this.


To resolve this issue I'm thinking to use the nodemailer for email service.

**Comment by AnitSarkar123** [comment]
I write the issue first please assign me first

**Comment by abhay-raj19** [comment]
i think so that there is some issue opened prior to this issue , if not do let me know , and join the discord community

**Comment by AnitSarkar123** [comment]
Ok..@abhay-raj19

**Comment by AnitSarkar123** [comment]
I know @abhay-raj19 issue number is #84 but the styling is bad as well as there has no sent mail functionality in the contact us page

**Comment by abhay-raj19** [comment]
Okay Proceed with the idea @AnitSarkar123 , will see to the PR.

**Comment by abhay-raj19** [comment]
Do Join our Discord Community and Get help with all the other contributors though.

**Comment by AnitSarkar123** [comment]
Thanks @abhay-raj19 please give me the server link of discord

**Comment by abhay-raj19** [comment]
> Thanks @abhay-raj19 please give me the server link of discord

Check up the Readme.Md

**Comment by abhay-raj19** [comment]
just work on the functionallity of sending up the mails for the Contact us Form.
