### ISSUE TITLE
the image backgruond interference in dark mode

### ISSUE THREAD

**Issue by krishkh** [abhay-raj19/FitBody#168]
Hi again, 
![image](https://github.com/abhay-raj19/FitBody/assets/51072063/c1d7d7f6-dd49-42c6-b1c5-3a34dd36a6bf)
if you look at this image you will see the white background behind this image,  you have this image without background but the similar image above has no background
![image](https://github.com/abhay-raj19/FitBody/assets/51072063/e9beb27b-7c10-44da-a643-f50d4991cb55)
I have fixed this issue in the first image and made it a backgroundless image
please assign this issue to me with the appropriate level and i will raise the pr right away

**Comment by dhruv389** [comment]
please checkout this issue #105 , which is already created and assigned

**Comment by krishkh** [comment]
> please checkout this issue #105 , which is already created and assigned

Ohhh ohk ohk then should i close my request?

**Comment by abhay-raj19** [comment]
//duplicate issue
