### ISSUE TITLE
Add Hamburger Icon for Mobile Navbar

### ISSUE THREAD

**Issue by ayushichoudhary-19** [abhay-raj19/FitBody#17]
**Description:**

Enhance mobile user experience by adding a hamburger icon to the navbar. Clicking the icon should reveal the navigation menu for easy access on smaller screens.

**Note:**

I'd like to take on this task. Please assign it to me.

**Comment by abhay-raj19** [comment]
Thats good issue.
Go for it @ayushichoudhary-19 🚀

**Comment by abhay-raj19** [comment]
Pls raise the PR ASAP.

**Comment by abhay-raj19** [comment]
@ayushichoudhary-19 ??

**Comment by ayushichoudhary-19** [comment]
Hello @abhay-raj19 I'm currently in the midst of some exams, which are demanding my full attention until the 26th. I apologize for any inconvenience this may cause regarding the issue. I can work on this after 26th but if someone else wants to work on it in the mean time, I'm absolutely fine with it. Please consider marking this issue with 'up-for-grabs' if the feature needs an urgent addressing. Sorry for the delay though. Thankyou.

**Comment by keshav-gupta19** [comment]
Can i do this?? @abhay-raj19
