### ISSUE TITLE
pricing section needs some improvement 

### ISSUE THREAD

**Issue by reshamsai150** [abhay-raj19/FitBody#172]
In the pricing section cards or static some improvement is needed like adding hovering effects 
assign this issue to me @abhay-raj19

**Comment by abhay-raj19** [comment]
would look back to your changes , proceed 
Do join the discord community.

**Comment by reshamsai150** [comment]
@abhay-raj19  please add the level label

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
