### ISSUE TITLE
The Registration tab is not working. I would like to contribute in this issue.

### ISSUE THREAD

**Issue by Dhiya-Natarajan** [abhay-raj19/FitBody#176]
**Issue Description:**

Hey  @abhay-raj19 ! 👋 I've noticed that the Registration tab isn't functioning as expected, and I'm eager to roll up my sleeves and contribute to fixing it. Here's what I have in mind:

**Proposed Solution:**

I'm planning to create a dedicated web page that streamlines the registration process. This page will be designed to seamlessly gather all the necessary details from users, ensuring a smooth and hassle-free registration experience. Here's a brief outline of what I intend to include:

**_User-friendly Interface_:** Implementing an intuitive interface that guides users through the registration process step by step.

**_Input Validation_:** Adding robust input validation to ensure that all submitted data is accurate and complete.

**_Error Handling:_** Implementing error handling mechanisms to provide clear feedback to users in case of any issues during registration.

**_Data Storage:_** Setting up a secure backend system to store user registration data securely.

**_Integration_:** Integrating the new registration page seamlessly into the existing website, ensuring a cohesive user experience.

Looking forward to diving into this project and making a positive impact! Let's do this! 💪

**Comment by abhay-raj19** [comment]
Proceed @Dhiya-Natarajan
