### ISSUE TITLE
The gym pricing cards can be made to hover up and have extended shadows when cursor hovers on them.

### ISSUE THREAD

**Issue by Rakshit-gen** [abhay-raj19/FitBody#177]
We can make this part much better by making it hover up when user moves his cursor on it.

![image](https://github.com/abhay-raj19/FitBody/assets/64471316/71704617-47e1-4f3a-b1fa-2a10ce9563bf)

**Comment by abhay-raj19** [comment]
Proceed with it @Rakshit-gen 
Do join our Discord community for suggesting some good ideas though.

**Comment by Rakshit-gen** [comment]
Okay @abhay-raj19 I'm on discord btw do connect with me

**Comment by tejjhode** [comment]
I am able to make changes please assign me under GSSOC'24
