### ISSUE TITLE
Contact Us page is not accepting the lowercase

### ISSUE THREAD

**Issue by TBorundia** [abhay-raj19/FitBody#182]
Under GSSoC'24 I want to work over this issue of contact us page and even want to make other improvements. It is not accepting the lowercase in name, email and message and even invalid emails are accepting. I can even improve its UI.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
@TBorundia You can proceed with it.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .

**Comment by TBorundia** [comment]
@abhay-raj19 Can you add me as a contributor, I am unable to push

**Comment by abhay-raj19** [comment]
> @abhay-raj19 Can you add me as a contributor, I am unable to push

Raise up the PR , that is possible in anyones project .

**Comment by Snehapandey07** [comment]
please assign me this issue under GSSOC 24
