### ISSUE TITLE
Icons in support section are not working

### ISSUE THREAD

**Issue by TBorundia** [abhay-raj19/FitBody#183]
Icons of facebook, instagram and other icons does not work. So if you provide the links , then I can make them functional . Under GSSoC'24 I want to work over this issue, please assign it to me.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
there are no accounts been formed on the social platforms .
first of all account on the platform are to be made and specifically linked with it .
if you are comfortable in forming accounts on the platform then you can proceed with it .

**Comment by shristipandey128** [comment]
Please assign me this

**Comment by ShreyashKathade** [comment]
is this issue done?

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhay-raj19** [comment]
whats your stats for the PR @TBorundia ?

**Comment by TBorundia** [comment]
@abhay-raj19 Sir,
To proceed, I need the following details:
Contact Number: A phone number to be used for account verification.
Email Address: An official email address to register the accounts.
Even to create new email address , Contact number verification is required. I have tried but unable to procced without this and I had also mailed you for this. 
Alternatively, if these accounts have been created, could you please share the credentials with me so that I can link them with the website and complete my task?
