### ISSUE TITLE
Change the menu icon from bars to × when the nav is open

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [abhay-raj19/FitBody#185]
In mobile when the nav is open then menu icons is remains same. It would be more interactive if that icon changes to ×bwhen the nav opens.

Can you please assign this issue to me under GSSOC'24?

**Comment by abhay-raj19** [comment]
Good to go @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Thank you @abhay-raj19.
