### ISSUE TITLE
To Add a preloader to website 

### ISSUE THREAD

**Issue by dhairyagothi** [abhay-raj19/FitBody#188]
Hey this website should have a preloader to make user experience good 
please assign this to me @abhay-raj19

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
@dhairyagothi Good to go , Assigned

**Comment by DownOnCoffee** [comment]
I've noticed that your website could benefit from enhanced user experience during load times. To address this, I would like to implement a preloader that appears while the page's resources are loading. This will improve overall aesthetic of our site .
this task aligns well with my skills, and I am eager to take it on. Could you please assign this task to me? I am in GSSOC'24.

**Comment by dhairyagothi** [comment]
> @dhairyagothi Good to go , Assigned

it is not assigned i think

**Comment by shristipandey128** [comment]
Hey Please assigned @abhay-raj19

**Comment by dhairyagothi** [comment]
Please add some assignee @abhay-raj19

**Comment by DownOnCoffee** [comment]
@abhay-raj19 I explained you here what I am going to do, can you please assign me this task ?

> I've noticed that your website could benefit from enhanced user experience during load times. To address this, I would like to implement a preloader that appears while the page's resources are loading. This will improve overall aesthetic of our site . this task aligns well with my skills, and I am eager to take it on. Could you please assign this task to me? I am in GSSOC'24.

**Comment by dhairyagothi** [comment]
Please add some assignee @abhay-raj19

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by Tejsvapandey1** [comment]
@abhay-raj19 hi sir i have already worked on this type of problem i can work on this

**Comment by abhay-raj19** [comment]
Rasise up the PR @dhairyagothi ASAP.

**Comment by dhairyagothi** [comment]
i have created pull request page loader added #382
