### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [abhay-raj19/FitBody#193]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet(using Github Bots) users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
Sure you can proceed with the idea @sanmarg

**Comment by sanmarg** [comment]
Task done.
