### ISSUE TITLE
Mouse Transition Effect

### ISSUE THREAD

**Issue by MitulSonagara** [abhay-raj19/FitBody#195]
As your website appearance is too good and futuristic. I will add some cursor effects like which will enhance the website looks.
I already contributed on many projects for this so i have much experience to do this work so please assign me this task.

**Comment by nikki-05** [comment]
Hello Sir, this transition within a website can make it interactive and I can make this for a better user experience, so Please assign this task to me.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
Can you show me some sort of examples for it that u have contributed though

**Comment by nikki-05** [comment]
> Can you show me some sort of examples for it that u have contributed though

Sir, though this is my first time participating and contributing therefore I don't have proof of that although I can show some examples of the transitions I made 
![Untitled video - Made with Clipchamp](https://github.com/abhay-raj19/FitBody/assets/109809432/932a26dd-2231-4d3c-bdfe-89184c410fb4)

**Comment by abhay-raj19** [comment]
Hey @MitulSonagara can you raise that same PR once again!

**Comment by MitulSonagara** [comment]
@abhay-raj19 Yes i can... but what happened

**Comment by MitulSonagara** [comment]
For making pull request again, should i upstream my fork and them make pull request?
Or the same pull request?

**Comment by MitulSonagara** [comment]
@abhay-raj19 I upstream the fork and made pull request again. But this is giving me this error 
![image](https://github.com/abhay-raj19/FitBody/assets/95460188/29017d50-d8c9-4f9b-80d7-09837aba640b)
