### ISSUE TITLE
Blogs backend

### ISSUE THREAD

**Issue by ayann07** [abhay-raj19/FitBody#197]
One of the features of fitbody is Blog and Articles: Publish informative articles and blog posts related to fitness, health, and wellness.
So I will be writing backend for this such that users can add blogs, delete blog, read blogs of other users etc. I 'll write write whole backend for this .
Please assign me I'll be doing this under GSSOC'24.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
looks great idea for adding blogs though but will redirect the new page for it not in the main webpage . 
you can proceed with it @ayann07

**Comment by ayann07** [comment]
Sure 👍

**Comment by KushagraKatiha** [comment]
@abhay-raj19 please assign this task to me. I am a GSSoC contributor also I have been working on this kind of solution for 1 week I am making my personal blogging application so please allow me to do this.

**Comment by ayann07** [comment]
@KushagraKatiha This issue is already assigned to me and I have made half of the stuff, so kindly take some other issue.

**Comment by ayann07** [comment]
@abhay-raj19 kindly close this issue since this pr for this is already merged.

**Comment by jahnaviyallamelli** [comment]
please assign this task to me
