### ISSUE TITLE
Adding blur effect.

### ISSUE THREAD

**Issue by Mayur-666** [abhay-raj19/FitBody#198]
I want to add blur effect to the navbar, it'll look good with the project themes.

**Comment by Mayur-666** [comment]
@abhay-raj19  Please assign me this issue.

**Comment by Mayur-666** [comment]
@abhay-raj19  Please assign me this issue.

**Comment by abhay-raj19** [comment]
Good to go but , only the glassmorphic effect would be great 
for eg
https://tailwindcss.com/docs/blur

**Comment by Mayur-666** [comment]
yes I had that in my mind from starting.
