### ISSUE TITLE
Pricing registration not working

### ISSUE THREAD

**Issue by aditi-pai04** [abhay-raj19/FitBody#199]
Clicking on any of the pricing options does not lead to registration page. @abhay-raj19 Please assign me this issue as a contributor under GSSoC'24.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
@anshdeep0504 brother just by commenting on each issue won't lead to the assignment to work on the issue , these are some what called as bad practice in the opensource contributing journey 
Try too go the project and search for bugs and good issues for it .

**Comment by abhay-raj19** [comment]
//Duplicate issue won't work
