### ISSUE TITLE
[Feature] Responsiveness for the whole website

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#2]
Add responsiveness among the whole components 

most requested is mobile responsiveness.

Happy Contributing Hactoberfest'23🤗

firstly get assigned and then raise Up a PR.

**Comment by Basavarajakjbasuu** [comment]
I will work on this issue feel free to assign me

**Comment by Saifullah00** [comment]
I too want to work on this issue, it'll be great to work on responsiveness if you assign me.
Thanks

**Comment by abhay-raj19** [comment]
@Basavarajakjbasuu Go for it now and create up a different branch for it . 
// Assigned

**Comment by Basavarajakjbasuu** [comment]
Thank you for assisting, I already started yesterday itself. I will raise PR as soon as possible.

**Comment by abhay-raj19** [comment]
@Basavarajakjbasuu what's the status for PR.

**Comment by Basavarajakjbasuu** [comment]
Sorry I got fever so I didn't able to work,  now this website is almost responsive and let me where i need to work on
