### ISSUE TITLE
margin issue

### ISSUE THREAD

**Issue by Harshitazz** [abhay-raj19/FitBody#202]
![Screenshot 2024-05-14 203340](https://github.com/abhay-raj19/FitBody/assets/118474653/df351634-ff73-4f54-81d4-be1ad60df22f)
weird right margin

**Comment by abhay-raj19** [comment]
it looks good to me though 
![image](https://github.com/abhay-raj19/FitBody/assets/96302417/79ba171a-a41e-48db-be2f-9ad1a8a356b1)
 it might be the issue with your side

**Comment by Harshitazz** [comment]
its in lower widths prevelant in mobile view
