### ISSUE TITLE
Payment gateway not integrated!

### ISSUE THREAD

**Issue by ShoveetSingh** [abhay-raj19/FitBody#206]
Hey mate shoveet here,after visiting your website with great ui/ux design and clicking on join now option it did not have any functionality. No payment gateway is integrated in your website.
I could easly add seamless payment gateway into your application to make it more realistic.
I am a gssoc contributor of 2024 and want to fix this issue.
Kindly reply whether i should work on it or not.
Thank you.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by abhay-raj19** [comment]
//Duplicate issue
someone is been assigned the same issue and working on the issue
