### ISSUE TITLE
Lot of unecessary space above and below the form.

### ISSUE THREAD

**Issue by sharmi4590** [abhay-raj19/FitBody#207]
Hello @abhay-raj19 
There's so much unnecessary space which is left not being used, Removing it will enhance the UI.
![Screenshot (395)](https://github.com/abhay-raj19/FitBody/assets/102676949/57527dd2-bee6-4df4-a71b-503cf4656770)
![Screenshot (396)](https://github.com/abhay-raj19/FitBody/assets/102676949/befd6276-a60c-48b0-9ef5-a80ab777f3db)
I am a GSSoC'24 contributor.

**Comment by abhay-raj19** [comment]
Go for it @sharmi4590

**Comment by KushagraKatiha** [comment]
I can fix it up, please @abhay-raj19 assign this task to me. I am a GSSoC contributor.
