### ISSUE TITLE
Admin Dashboard Frontend

### ISSUE THREAD

**Issue by Paarisha1** [abhay-raj19/FitBody#208]
As the backend of Admin Dashboard has been designed So I will design the frontend of admin dashboard

**Comment by shristipandey128** [comment]
Please assign me this issue @abhay-raj19

**Comment by Ayushhgupta39** [comment]
@Paarisha1 You may proceed.

**Comment by Paarisha1** [comment]
Sure

**Comment by sameer1098alam** [comment]
do we have have to choose specific part in the project project or if there is any issue  then we can resolve together
whether it is frontend or backend

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
