### ISSUE TITLE
Hero img is not responsive on smaller devices.

### ISSUE THREAD

**Issue by akssshh** [abhay-raj19/FitBody#21]
![Screenshot 2023-10-04 at 1 23 08 AM](https://github.com/abhay-raj19/FitBody/assets/91525166/f3be1883-9429-4afe-bdc2-70ea284ccc05)

**Comment by akssshh** [comment]
@abhay-raj19 Please assign this issue to me.

**Comment by abhay-raj19** [comment]
go for it now @akssshh

**Comment by adityakumar68** [comment]
is anyone working on it or i can contribute ?? 
i can fix this

**Comment by akssshh** [comment]
Hey @abhay-raj19 is it ok?? 

![Screenshot 2023-10-06 at 1 29 52 PM](https://github.com/abhay-raj19/FitBody/assets/91525166/568c9d70-f46c-4bbe-89a1-7d2936a52aea)

**Comment by akssshh** [comment]
hey @abhay-raj19 i have submitted a pull request #25 for the issue #21
