### ISSUE TITLE
GSSOC | Feature -> Adding Page for Healthy Diet Plans

### ISSUE THREAD

**Issue by satyam8932** [abhay-raj19/FitBody#210]
Hi @abhay-raj19  
I want to create another feature to add a page where we can provide free diet plans to users, just like we done for workouts.

OLD Feature got Merged - https://github.com/abhay-raj19/FitBody/issues/126

Please assign this to me and labels gssoc, enhancement and level3 bro

Thanks
Satyam

**Comment by satyam8932** [comment]
Please assign me this issue bro

**Comment by jessicachawla** [comment]
@abhay-raj19 please assign if you think this is fine.

**Comment by satyam8932** [comment]
hey @Ayushhgupta39  can you add gssoc, level labels please

**Comment by satyam8932** [comment]
Hey @Ayushhgupta39  i will create a complete new feature with new architecture which is a lot more work so can you please add level 3 label, as for the same kind of work Abhay assigned me level 3 badge

Hope you will understand
Thanks

**Comment by satyam8932** [comment]
I made a PR https://github.com/abhay-raj19/FitBody/pull/279

Please check this and approve it bro

Thanks
Satyam
