### ISSUE TITLE
Social Media links are not working in the footer!!!

### ISSUE THREAD

**Issue by Vanshika7902** [abhay-raj19/FitBody#212]
Social Media links are not working in the footer.

![WhatsApp Image 2024-05-15 at 12 49 30 PM](https://github.com/abhay-raj19/FitBody/assets/92636041/b18c4394-3ea5-4aa3-9d5f-7660f7555c2e)

**Comment by DownOnCoffee** [comment]
As an experienced frontend developer, I also identified this crucial issue on your website where the social media links are not working. This affects your connectivity with the audience.
To address this, I would like to correct the links to ensure they are operational.This task aligns well with my skills, and I am eager to take it on as part of my contributions in GSSOC'24. Please assign me this tasks
Solution- Send me your social links and I will add automatic navigation through the website to those social pages
