### ISSUE TITLE
Navbar not working in Workouts For Free section

### ISSUE THREAD

**Issue by UjjwalGupta1105** [abhay-raj19/FitBody#213]
The navbar is not working in **Workouts For Free** section

![123](https://github.com/abhay-raj19/FitBody/assets/165131091/b96a90a8-d04c-4c42-bb6a-5db25d5dee68)

**Comment by Ayushhgupta39** [comment]
@UjjwalGupta1105 Do you want to work on this?

**Comment by UjjwalGupta1105** [comment]
Yes , I want to work on this , Please assign it to me .

**Comment by UjjwalGupta1105** [comment]
Please assign me the task .

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
