### ISSUE TITLE
To Enhance the  Workouts For Free Page 

### ISSUE THREAD

**Issue by Vanshika7902** [abhay-raj19/FitBody#215]
To Enhance the **Workouts For Free Page** like enhancing hovering effect , giving proper spaces where needed .

![Screenshot (697)](https://github.com/abhay-raj19/FitBody/assets/92636041/e80fd53f-b8ac-44d3-87ab-ffcd9682d946)

![Screenshot (698)](https://github.com/abhay-raj19/FitBody/assets/92636041/68c2a2ab-277c-471b-a565-789b886abfcf)

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhay-raj19** [comment]
The UI for this complete page would be changed as there are some of the gaps in the right side of the page.
