### ISSUE TITLE
No support section 

### ISSUE THREAD

**Issue by DownOnCoffee** [abhay-raj19/FitBody#217]
There is no support section in the footer. On clicking it , It just scrolls to the top of the website.

**Comment by DownOnCoffee** [comment]
As an experienced frontend developer, I've noticed that our website currently lacks a dedicated support section.
To enhance user satisfaction and accessibility, I propose to design and implement a comprehensive support section that provides helpful information, FAQs, and contact options,whatever you want , You can send me the content. This task aligns well with my skills, and I am eager to take it on as part of my contributions in GSSOC'24. Could you please assign this task to me?

**Comment by Ayushhgupta39** [comment]
Go ahead @DownOnCoffee

**Comment by DownOnCoffee** [comment]
@Ayushhgupta39 Can you add the required labels? And also provide me with the content you want in that section and your contact information that I will add.

**Comment by Ayushhgupta39** [comment]
> @Ayushhgupta39 Can you add the required labels? And also provide me with the content you want in that section and your contact information that I will add.

You are free to write the content of your own. You can use GPT or search the internet for this. Leave the form action as empty (#) for now.

**Comment by Ayushhgupta39** [comment]
> @Ayushhgupta39 I have decided that in the support section , I will be adding some FAQ'S and a form to submit the issue faced by any customer. These are the FAQ'S -> How can I upgrade my current plan? How often are new free workout videos added? Can I cancel my subscription at any time and get refund? Who can I contact if I have issues or need support with my plan? Do you offer nutritional advice or meal plans to complement the workout programs? What qualifications do the trainers in the gym have? Are there any age restrictions for using the gym plan?
> 
> So I plan to design and implement the faq section on the website and then you can fill the information/answers . Are these questions fine?

Great, go ahead

**Comment by DownOnCoffee** [comment]
@Ayushhgupta39 I am pushing my code in another branch but I also focus on the consistency in github graph , thus when i push code in the another branch except main branch , the contributions are not updated in the github graph , Thus can I merge those commits in main branch of forked repo or should I not?

**Comment by DownOnCoffee** [comment]
![Screenshot (1283)](https://github.com/abhay-raj19/FitBody/assets/94672955/8eb80616-1f1b-4f87-9709-b6d4b49d25a1)
I have implemented the FAQ section , You can tell if something needs to be changed.
I have put the FAQ just below the contact section , I am thinking to add a link under FAQ's which directs to contact section and the user can send the issue there are facing directly through contact form. 
OR
I can implement another form if you want.

**Comment by Ayushhgupta39** [comment]
> @Ayushhgupta39 I am pushing my code in another branch but I also focus on the consistency in github graph , thus when i push code in the another branch except main branch , the contributions are not updated in the github graph , Thus can I merge those commits in main branch of forked repo or should I not?

@abhay-raj19 check this out

**Comment by Ayushhgupta39** [comment]
> @Ayushhgupta39 I am pushing my code in another branch but I also focus on the consistency in github graph , thus when i push code in the another branch except main branch , the contributions are not updated in the github graph , Thus can I merge those commits in main branch of forked repo or should I not?

I guess you can, You can push it directly into your fork, and from there onwards you can raise a PR

**Comment by DownOnCoffee** [comment]
> ![Screenshot (1283)](https://private-user-images.githubusercontent.com/94672955/333083905-8eb80616-1f1b-4f87-9709-b6d4b49d25a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTk1MTcsIm5iZiI6MTcxNjYxOTIxNywicGF0aCI6Ii85NDY3Mjk1NS8zMzMwODM5MDUtOGViODA2MTYtMWYxYi00Zjg3LTk3MDktYjZkNGI0OWQyNWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA2NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Y2RhMDM5Yzc4YjlhOTBiZjJiYjExMzRkOTYyMjRiM2I3ODY0MmFjNGIwMTdhYjkwMTA3MGFkODUzM2E3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlZ5gi4mu1T-GXY_6IWoU3t_jo7Avd84SATbRS5pAVY) I have implemented the FAQ section , You can tell if something needs to be changed. I have put the FAQ just below the contact section , I am thinking to add a link under FAQ's which directs to contact section and the user can send the issue there are facing directly through contact form. OR I can implement another form if you want.

@abhay-raj19 @Ayushhgupta39  okay so I will be merging in main branch in the forked repo and Can you reply to this?

**Comment by Ayushhgupta39** [comment]
Go ahead, after that you can raise a PR

**Comment by DownOnCoffee** [comment]
@Ayushhgupta39 Okay should I add a link below these FAQ'S which can direct user to the contact section?
