### ISSUE TITLE
Add "Become a Member" Page 

### ISSUE THREAD

**Issue by MastanSayyad** [abhay-raj19/FitBody#223]
Hi @abhay-raj19 ,
I've noticed that the **website includes a "Become a member" link in the footer**, but currently, there is no corresponding page for users to navigate. 

![image](https://github.com/abhay-raj19/FitBody/assets/101971980/68063deb-a98d-4667-9c9e-b7129271e0c9)

To improve website navigation and user experience, I propose creating and implementing a dedicated "Become a Member" page.

**Benefits**:
- "Become a Member" page encourages users to explore membership options
-   Improved user engagement
-   Increase customers

Could you **please assign this issue to me under GSSoC'24** so I can contribute to the project?

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
