### ISSUE TITLE
Testimonials section not responsive on smaller devices.

### ISSUE THREAD

**Issue by akssshh** [abhay-raj19/FitBody#23]
![Screenshot 2023-10-05 at 8 32 55 PM](https://github.com/abhay-raj19/FitBody/assets/91525166/ccbd5dcd-716a-4539-a51f-8674435ad9f6)
<br>
Testimonials section is not responsive on smaller devices due to which there is horizontal scrolling!!

**Comment by Albert-2** [comment]
I think i got it can you please assign me this issue....!
Thank You....

**Comment by abhay-raj19** [comment]
go for it @akssshh

**Comment by akssshh** [comment]
@abhay-raj19 assign it to @Albert-2 as i am busy on some other projects.

**Comment by hamzailyas237** [comment]
It this issue still persists, assign it to me.

**Comment by Piyush07p** [comment]
can you assign it to me if this issue still remains
