### ISSUE TITLE
Text Visibility Issue in Dark Mode for "Read and Review" Box

### ISSUE THREAD

**Issue by Pratikchaudhari5** [abhay-raj19/FitBody#235]
Description:
When dark mode is enabled, the text in the "Read and Review" box is not visible, making it difficult for users to read the content.
As content seems to be disappears
This issue affects the readability and user experience in dark mode, making it important to fix.

Expected Behavior:
The text in the "Read and Review" box should be clearly visible in dark mode.
![image](https://github.com/abhay-raj19/FitBody/assets/104305163/d364eb78-d27a-4988-8d2d-b18162fbc700)

please assign me this issue.

**Comment by root-0101** [comment]
Hey @abhay-raj19 please assign me this issue
