### ISSUE TITLE
Bug in Navbar

### ISSUE THREAD

**Issue by rahul1841** [abhay-raj19/FitBody#237]
Problem/Bug :- 
When user clicks on the logo present in the Navbar , white screen is appearing.

Solution :-
I will add functionality that by clicking in logo of Navbar user can come on the Homepage not matter on which he/she is 
and removes white screen issue.

@abhay-raj19  please assign this to me , I want to work on this issue.

**Comment by anuragnegi000** [comment]
I have created a PR, please look into it...!

**Comment by rahul1841** [comment]
@abhay-raj19  please assign it to me , i will fix it ASAP

**Comment by IsmartGaurav** [comment]
Please assign to me

**Comment by anuragnegi000** [comment]
@abhay-raj19 hello abhay, you said create a new PR, may i know what's the reason behind it?

**Comment by anuragnegi000** [comment]
@abhay-raj19 check PR and please ADD label in it
