### ISSUE TITLE
Request to Add FAQ Section in Navbar

### ISSUE THREAD

**Issue by SrijaVuppala295** [abhay-raj19/FitBody#242]
There's a need to address frequently asked questions (FAQ) but no dedicated section in the navbar, leading to difficulty in accessing important information efficiently.

## Solution Description:
Integrate a FAQ section into the navigation bar to provide easy access to commonly asked questions and relevant information.

## Alternatives Considered:
Utilizing a separate page or link for FAQs, or embedding FAQ content within existing pages.

## Screenshot 
Similar to this type of section

![Screenshot 2024-05-17 003442](https://github.com/abhay-raj19/FitBody/assets/140592148/e69bd880-281f-4a26-ae84-b0251517704c)

**Comment by nishant0708** [comment]
hey assign me this issue under gssoc 2024

**Comment by SrijaVuppala295** [comment]
Sure !!!
