### ISSUE TITLE
Navbar is not working properly /Routing error

### ISSUE THREAD

**Issue by anshkie** [abhay-raj19/FitBody#244]
Navbar is not working after we click on the get Started button in Home page. After clicking on any button from get started page. 
The navbar buttons are completely useless
![fitbody](https://github.com/abhay-raj19/FitBody/assets/122461318/fecf414b-22e0-43c9-b549-9f7a00825052)

**Comment by anshkie** [comment]
@abhay-raj19 please assign this issue to me under GSSoc 2024 as I have already faced similar issue

**Comment by Dhevamuthu** [comment]
please assign this issue for me under gssoc 2024

**Comment by prachi-kCoder** [comment]
i am quite efficient in fixing the routing errors, I fix it.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhay-raj19** [comment]
it is working correctly can u upload a short video for it the issue with it

**Comment by anshkie** [comment]
Uploading FitBody - Google Chrome 2024-05-24 11-28-49.mp4…

here in this video it can be clearly seen that after getStarted button the navbar is not working
