### ISSUE TITLE
add logo in title barr

### ISSUE THREAD

**Issue by shuhaki** [abhay-raj19/FitBody#248]
lease assign me i want to do.......

**Comment by prachi-kCoder** [comment]
I can add the logos and want to  improve overall styling of it and fix some spaces. Do-able for me.

**Comment by Dhevamuthu** [comment]
please assign the issue for me under gssoc 2024

**Comment by 143divya** [comment]
I'm new to open source and it's my first time in GSsoc. Can you please assign me this issue?

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhay-raj19** [comment]
it is there 

![image](https://github.com/abhay-raj19/FitBody/assets/96302417/82c29b4a-90d0-42bd-8734-f790fe70dfbf)
