### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [abhay-raj19/FitBody#249]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by abhay-raj19** [comment]
//Duplicate issue

**Comment by suhanipaliwal** [comment]
But I was the one who raised this issue first. Why would you label the original issue as duplicate???

**Comment by suhanipaliwal** [comment]
All the other PR template related issues have been raised after this issue only.
