### ISSUE TITLE
inconsistency in the main page girl photos

### ISSUE THREAD

**Issue by krishkh** [abhay-raj19/FitBody#260]
![image](https://github.com/abhay-raj19/FitBody/assets/51072063/10493770-f355-4f18-a819-90f7e1ea8315)
why is the image black here from inside and white in the pic below
![image](https://github.com/abhay-raj19/FitBody/assets/51072063/744ddac3-bd6d-4dca-8463-8fa1f7eeeceb)

If you think this needs to be changed, please assign me the issue

**Comment by abhay-raj19** [comment]
can be changed up though ?

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .

**Comment by krishkh** [comment]
> can you please assign me under GSSOC.'24 .

it is already assigned to me, miss

**Comment by krishkh** [comment]
> can be changed up though ?

But why? 💀
