### ISSUE TITLE
text visibility in contact me when turned to dark mode

### ISSUE THREAD

**Issue by krishkh** [abhay-raj19/FitBody#261]
![image](https://github.com/abhay-raj19/FitBody/assets/51072063/b9117a2e-69a2-4c4a-8aac-b2dae700605b)
The text should be white here, when turned to dark mode. unlike staying black like it is in light mode

please assign me this issue under gssoc'24

**Comment by abhay-raj19** [comment]
Fix it up ASAP

**Comment by Tejsvapandey1** [comment]
@abhay-raj19 Sir I would like to work on this issuee

**Comment by krishkh** [comment]
> @abhay-raj19 Sir I would like to work on this issuee

This issue is assigned to me and i have already raised the pr
