### ISSUE TITLE
Feat: Improve Dark Mode Consistency and Fix Typos

### ISSUE THREAD

**Issue by Naitik2929** [abhay-raj19/FitBody#267]
**Issues to Address**:

1. **Dark Mode Consistency**:
    - Ensure that if the home page is in dark mode, the classes page and all other pages should also be in dark mode for a consistent user experience.
2. **Typographical Errors**:
    - Correct the spelling like in the hero section spelling of "benefits".
3. **Dark Mode Readability**:
    - Improve the readability of testimonials in dark mode, as the current color scheme makes the text difficult to read.
4. **Navigation Issue**:
    - Fix the issue where clicking on the logo redirects to "/&". It should navigate to the home page or a specified valid route.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhay-raj19** [comment]
All are fixed up though now
