### ISSUE TITLE
Gif of different exercises

### ISSUE THREAD

**Issue by ankitgupta143** [abhay-raj19/FitBody#270]
@abhay-raj19 I add the Gif using exercise api so that user can easily do exercises by looking up to gif
![gif](https://github.com/abhay-raj19/FitBody/assets/114281117/d6e2bfd4-49d4-4648-9ad6-80f04c49c694)

**Comment by abhay-raj19** [comment]
Actully the video solution is the better approach for this that someone has initilised up in the get started section
