### ISSUE TITLE
In the Dark Mode, Reviews and Ratings are not visible

### ISSUE THREAD

**Issue by aditi9402** [abhay-raj19/FitBody#272]
![Screenshot (720)](https://github.com/abhay-raj19/FitBody/assets/114405540/f63888e1-dc75-47d8-bab1-ad0a4af9641a)

I can fix this. Please assign me this issue under gssoc 24.

**Comment by abhay-raj19** [comment]
Proceed with the issue @aditi9402

**Comment by Hitesh4278** [comment]
Hi @abhay-raj19  can you please assign this issue to me?

**Comment by aditi9402** [comment]
@Hitesh4278 @abhay-raj19  I've already completed it and raised a PR as well.

**Comment by Hitesh4278** [comment]
Okay.
