### ISSUE TITLE
In mobile the register and watch video buttons overlap . 

### ISSUE THREAD

**Issue by 2115425Amar** [abhay-raj19/FitBody#273]
I want to fix the issue please @abhay-raj19  assign me for the project.
![Screenshot 2024-05-18 235511](https://github.com/abhay-raj19/FitBody/assets/113373133/d567f244-71b6-4772-9ddd-6d474d6b3b70)

**Comment by Sujal7ss** [comment]
Is this issue still pending??
Please assign it to me @abhay-raj19

**Comment by crazyshrut** [comment]
hey @abhay-raj19 , I am a gssoc contributor, Please assign this to me
