### ISSUE TITLE
Add Dockerfiles, Docker-Compose files for both Dev and Prod 

### ISSUE THREAD

**Issue by MishraTanishq619** [abhay-raj19/FitBody#276]
Issue: To Containerise the application

Covering issue #89 

- [ ] Adding dockerfile for web ("/")
- [ ] Adding dockerfile for server ("/server")
- [ ] Adding Docker-compose file for Development server. ("Docker-Compose.Dev.Yaml")
- [ ] Adding Docker-Compose file for Production server. ("Docker-Compose.Prod.Yaml")
- [ ] Adding ".env.example" file if needed.
- [ ] Updating ReadMe.md , adding instructions to start the container.

**Comment by MishraTanishq619** [comment]
I was assigned to do issue #89 
So on the way I am doing this issue,
Please assign this issue to me for GSSOC

I am just making a PR for this.

**Comment by agarwalhimanshugaya** [comment]
if this issue is not completely kindly assign to me so that i can work on this issue

**Comment by MishraTanishq619** [comment]
@agarwalhimanshugaya 
Can you Please add Hacktoberfest and Hacktoberfest accepted to this Issue and PR.
This would help me for hacktoberfest 2024.
