### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by aasthakourav20** [abhay-raj19/FitBody#282]
What's missing in this repository!!

Adding an issue template file to a repository is a practice that benefits both the maintainers and the contributors of a project. Here are several key reasons why this is important:

1. Standardization and Consistency
An issue template helps ensure that every issue submitted follows a consistent structure. This makes it easier for maintainers to review and address issues since they can quickly find the relevant information.

2. Improved Clarity and Detail
Templates guide contributors to provide all necessary details. They can include sections for the issue description, steps to reproduce, expected behavior, actual behavior, environment details, and any relevant screenshots or logs. This reduces the back-and-forth communication needed to gather essential information.

3. Efficient Triage
With all the required information in place, maintainers can triage issues more efficiently. They can quickly determine the severity, priority, and required resources to address the issue.

4. Better User Experience
For contributors, especially new ones, templates offer a clear and guided way to report issues. This lowers the barrier to entry for contributing to the project and ensures that their reports are more likely to be acted upon.

5. Reduced Duplicate Issues
By including a checklist or reminders in the template to search for existing issues before submitting a new one, the occurrence of duplicate issues can be minimized. This helps maintain a cleaner issue tracker.

Kindly assign this issue to me under GSSoC'24

**Comment by Ayushhgupta39** [comment]
Duplicate #268
