### ISSUE TITLE
Subscription Based Payment Activation Using Stripe

### ISSUE THREAD

**Issue by neelamnagarajgithub** [abhay-raj19/FitBody#284]
![image](https://github.com/abhay-raj19/FitBody/assets/113004986/439c9e14-80db-4a62-be64-b769d80cf7be)

when we click on Join Now button User Will be First authenticated and then he will be taken to a payment Payment where he can start /renew his subscription

can you please assign this to me Under GSSOC'24??

**Comment by abhay-raj19** [comment]
You can proceed with the idea @neelamnagarajgithub

**Comment by abhay-raj19** [comment]
But what i think is that someone is working on this same issue pls check that

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .
