### ISSUE TITLE
Fix Navigation Bar Links and Add Back Button on "Get Started" Page

### ISSUE THREAD

**Issue by swetha5157** [abhay-raj19/FitBody#294]
# Issue: Fix Navigation Bar Links and Add Back Button on "Get Started" Page

## Description
The navigation bar links are currently not working on the "Get Started" page. Additionally, there is a need to add a back button to facilitate users in returning to the main page.

## Tasks
*  **Fix Navigation Bar Links:**
   - Ensure all links in the navigation bar are correctly referenced and functional.
   - Verify that the file paths are correct and accessible for all navigation links.

*  **Add Back Button:**
   - Add a back button on the "Get Started" page.
   - Ensure the back button redirects users to the main page (index.html).

## Expected Outcome
- All navigation bar links should work correctly and lead to the appropriate pages.
- The "Get Started" page should have a functional back button that takes users back to the main page.

![Get Started page](https://github.com/abhay-raj19/FitBody/assets/123291594/6e5d9641-d009-4d6f-b981-9b6333175f84)

**Comment by abhay-raj19** [comment]
you can work on adding up the back button functionallity as for navigation purposes .

**Comment by swetha5157** [comment]
Thankyou for assigning and kindly add level labels

**Comment by swetha5157** [comment]
RAISED PR kindly check it @abhay-raj19
