### ISSUE TITLE
Register Button not working, Register Functionality frontend and backend not connected

### ISSUE THREAD

**Issue by soham0005** [abhay-raj19/FitBody#295]
After click on Register button, no action is performed, I would like to implement that functionality

**Comment by soham0005** [comment]
Hello @abhay-raj19, can i work on this?

**Comment by DarshilManiya** [comment]
Hey,

After clicking the register button, nothing happens. This issue prevents new users from registering, which could hinder user acquisition. Can I work on this? If you allow me, I can fix this issue.

**Comment by abhay-raj19** [comment]
someone is been assigned up the same issue prior to it
