### ISSUE TITLE
Fix Navigation links

### ISSUE THREAD

**Issue by kesharwaniyanshi** [abhay-raj19/FitBody#296]
![image](https://github.com/abhay-raj19/FitBody/assets/123561974/d06edeff-3ff7-464a-9d58-3cc86af73482)
The links of navbar are not working on this page . Nothing happens on clicking on Home,Pricing , all other option.
Needs to be fixed.Please assign it to me.

**Comment by abhay-raj19** [comment]
it has been raised up by someone and someone is working on it
