### ISSUE TITLE
[Feat]: The Navbar is not Fixed of Workout Free page in below Tablet Veiw section

### ISSUE THREAD

**Issue by SrinivasDevolper** [abhay-raj19/FitBody#298]
1. The Navbar is not Fixed on the Workout Free page in the below Tablet View section.
2. we need to add up scroll button in the below Tablet View section. that will be more user-friendly experience.

1.**Actual Behavior:**
The **Navbar is not Fixed** on the Workout Free page in below Tablet Veiw section.

1.**Excepted Behavior:**
The **Navbar is Fixed** on the Workout Free page in below Tablet Veiw section.

2.**Actual Behavior:**
There is **not up scroll button** feature in the below Tablet View section.

2.**Excepted Behavior:**
There is an **up scroll button** feature in the below Tablet View section that will be more user-friendly experience.

I am GSSOC24 Contributor
please assign this issue, I would like to work on this issue

**I have sent two issues. In Case if another person raises this same issue please inform me and you can send another one issue to me in those two issues.**

**Comment by abhay-raj19** [comment]
You can work on it @SrinivasDevolper
