### ISSUE TITLE
[Module] Add multiple components for the options .

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#3]
Add multiple good UI components 

Like:
<img width="276" alt="image" src="https://github.com/abhay-raj19/FitBody/assets/96302417/82e61f42-8af8-4590-8677-e62b18539c24">
 for get started and watch video.

Happy contributing Hacktoberfest'23🤗.

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thank you.

**Comment by abhay-raj19** [comment]
for navbar links create a similar component for rendering it inside the website or 
for get started and watch video you can also create up the component .

**Comment by abhay-raj19** [comment]
Assigned @Atulsoam562003
