### ISSUE TITLE
After click on hamburger icons a box open up but after that cross icon should come in place of hamburger so user know to close that open box

### ISSUE THREAD

**Issue by kapilG0** [abhay-raj19/FitBody#302]
![Screenshot_20240523_135810](https://github.com/abhay-raj19/FitBody/assets/59639410/82b9fc06-88f3-4763-b159-2f64d37ba40a)

**Comment by kapilG0** [comment]
Hello @abhay-raj19 please assign this issue to me under gssoc 24

**Comment by abhay-raj19** [comment]
@kapilG0 go for the changes !!

**Comment by kapilG0** [comment]
Hello @abhay-raj19 i raised pr https://github.com/abhay-raj19/FitBody/pull/386. please check
