### ISSUE TITLE
Feature for auto commenting on a new issue creation

### ISSUE THREAD

**Issue by suhanipaliwal** [abhay-raj19/FitBody#305]
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by Ayushhgupta39** [comment]
Can you please explain more on what types of comments will be there?

**Comment by abhay-raj19** [comment]
@suhanipaliwal can you show me up that with some short video how it works and what types of comments will it raise up ?

**Comment by suhanipaliwal** [comment]
I will be adding a YAML file in the .github/workflows directory which will add the feature of auto commenting as soon as a new issue created. Whenever a new issue will be made, this comment will be added immediately on the issue.
<img width="902" alt="Issue comment" src="https://github.com/abhay-raj19/FitBody/assets/161575955/ae4dcb55-7750-462c-accf-e54861e89940">

**Comment by Ayushhgupta39** [comment]
Cool, Go ahead
