### ISSUE TITLE
Adding About Us page

### ISSUE THREAD

**Issue by Amruta7203** [abhay-raj19/FitBody#311]
I propose adding an About Us page for better user experience and link it to the footer.

**Comment by Amruta7203** [comment]
@abhay-raj19  Request you to assign this task to me under GSSOC'24.

**Comment by abhay-raj19** [comment]
Proceed with the idea @Amruta7203

**Comment by Amruta7203** [comment]
@abhay-raj19 Request you to add the gssoc labels.

**Comment by Amruta7203** [comment]
@abhay-raj19 add the relevant gssoc labels
