### ISSUE TITLE
Enhancing contact Us component UI in dark mode

### ISSUE THREAD

**Issue by Amruta7203** [abhay-raj19/FitBody#313]
![image](https://github.com/abhay-raj19/FitBody/assets/116087736/620b0160-8e97-4c14-a3da-00b161941e78)

The UI of contact us component needs to be improved.

**Comment by Amruta7203** [comment]
@abhay-raj19 Request you to assign this task to me under GSSOC'24

**Comment by abhay-raj19** [comment]
it looks good though, you can proceed with the functionallity of that same .

**Comment by Amruta7203** [comment]
@abhay-raj19 Request you to add the gssoc labels.
