### ISSUE TITLE
Personalized Nutrition Diet Plans Based on Gender and Age Group (18+)

### ISSUE THREAD

**Issue by Burugupalli-Yogitha** [abhay-raj19/FitBody#315]
I would like to  add a new feature that provides personalized nutrition diet plans based on the user's gender and age group, starting from 18 years old. This enhancement will help users maintain a balanced and healthy diet.

@abhay-raj19 
I would like to work on this issue.Could you please assign this issue

**Comment by divyadaya** [comment]
i would like to work on this issue. 
could you please assign this task to me ?
