### ISSUE TITLE
Adding the Rating section for the User

### ISSUE THREAD

**Issue by suraj-9849** [abhay-raj19/FitBody#318]
On exploring this website I just found out that the user cannot rate. so I thought like if the user can rate then it will be better so  please assign this issue to me under @gssoc @abhay-raj19

**Comment by abhay-raj19** [comment]
Can you show me some sort of template design for it ?

**Comment by Ayushi-Choudhary22** [comment]
Hey @abhay-raj19 I think I can add this feature & enhance the website. Please assign this issue to me under GSSOC 2024, I will try my best to add this new feature.
