### ISSUE TITLE
Fix repeated grid in Footer

### ISSUE THREAD

**Issue by Ayushhgupta39** [abhay-raj19/FitBody#32]
![image](https://github.com/abhay-raj19/FitBody/assets/96309609/2612b7fb-88b9-4cf0-8d48-cf1f219c2762)

The quick links grid is repeated in the footer section, which is not necessary. I want to fix this. Please assign me this issue.

**Comment by abhay-raj19** [comment]
Go for it @Ayushhgupta39

**Comment by its-kumar-yash** [comment]
@abhay-raj19 I want to work on this issue, please assign this to me

**Comment by Ayushhgupta39** [comment]
@its-kumar-yash I've already fixed this buddy. Just waiting for the PR to get merged! :)
