### ISSUE TITLE
There is an also some issues in the navigation bar the Register button doesn't work properly and also there must be a feedback button

### ISSUE THREAD

**Issue by himanshi-0908** [abhay-raj19/FitBody#323]
Issue in the register button and there must be an feedback button that help to you easily handle all the issue.

**Comment by himanshi-0908** [comment]
Hey Abhay-raj  assign me for this issue

**Comment by abhay-raj19** [comment]
though you can proceed with the feedback system if possible but open up the seperate issue for that

**Comment by himanshi-0908** [comment]
I raise issue but it's not assign to me under the GSSOC'24
