### ISSUE TITLE
Registration System Is Missing...

### ISSUE THREAD

**Issue by nishantmakwanaa** [abhay-raj19/FitBody#324]
@abhay-raj19 hello, there is no registration system is not present in the website. please assign me to add the features rich registration system.

![Screenshot 2024-05-25 213451](https://github.com/abhay-raj19/FitBody/assets/144738854/99794c8a-329b-4258-9aae-daec6469f352)

**Comment by abhay-raj19** [comment]
@nishantmakwanaa Proceed with the idea
