### ISSUE TITLE
Add a Register Page and Login Page

### ISSUE THREAD

**Issue by kesharwaniyanshi** [abhay-raj19/FitBody#332]
We can add a Register and Login page for better Visual appearance and User experience.Please assign me this task.

**Comment by surendar-05** [comment]
Heyy I want to work on this issue Assign me under GSSOC'24

**Comment by Unnati101** [comment]
please assign this issue to me

**Comment by Chetan8299** [comment]
Please assign this issue to me I can design a great login and register page using glassmorphism @abhay-raj19 please assign this issue to me under GSSOC'24

**Comment by abhay-raj19** [comment]
proceed with the idea @kesharwaniyanshi

**Comment by Samani-Humaira** [comment]
@kesharwaniyanshi  Have you completed the login and signup page?

 Once that's done, we can proceed with integrating it with the backend.

**Comment by kesharwaniyanshi** [comment]
Yes i have sent a PR for the same.
