### ISSUE TITLE
Bug : Header navigation link ae not working in the getting started page

### ISSUE THREAD

**Issue by Laxelspal** [abhay-raj19/FitBody#333]
**Description of the issue**
when we are in the getting started page ,  navigation link are not woring.

**Steps to Reproduce**
1- Go the getting started Page
2- Click on any of the header navigation link like home, contact, classes.
3- you will see none of them are working.

I can fix this. Please assign me this issue under gssoc 24.

**Comment by abhay-raj19** [comment]
Fix it up @Laxelspal
