### ISSUE TITLE
[Enhancement]: UI Fixes Required

### ISSUE THREAD

**Issue by Chetan8299** [abhay-raj19/FitBody#334]
- As you can see from the below image the text and input fields of contact us form are not properly visible

![image](https://github.com/abhay-raj19/FitBody/assets/167693543/1f28761e-d0bd-4be4-9348-9219bb8f0e1f)

- Also the page is overflowing in horizontal axis
![image](https://github.com/abhay-raj19/FitBody/assets/167693543/662bff50-ec6f-4709-b984-dcc39f16daa4)

- Dark Mode is not applied to the navbar dropdown menu 
![image](https://github.com/abhay-raj19/FitBody/assets/167693543/951cbf5d-3185-4000-bd5c-ea72895ec6d6)

- Image z-index is also not great some times it overlaps the dropdown and sometimes it doesn't which does not give a good feel
![image](https://github.com/abhay-raj19/FitBody/assets/167693543/a7a57b97-5e52-4104-879b-9ac6724debec)
![image](https://github.com/abhay-raj19/FitBody/assets/167693543/55aeb9f5-5393-4053-9e82-c13302fc102d)

Please Assign this issue to me under GSSOC'24.

**Comment by abhay-raj19** [comment]
Correct it up ASAP

**Comment by itz-mohit-014** [comment]
I am a GSSoc contributor. I have seen your website Fitbody. Chetan has found the issues and you also assigned them but I think Chetan is not active here so could you please assign it to me? 
I would be very glad to work on it So could you please assign it to me ASAP

![Screenshot (248)](https://github.com/abhay-raj19/FitBody/assets/95575123/79fab8c7-5951-489e-b49e-cdab112e4aff)
![Screenshot (249)](https://github.com/abhay-raj19/FitBody/assets/95575123/cf5e4eb2-0ff7-466d-8e4d-c5a1eb406193)
![Screenshot 2024-06-18 164124](https://github.com/abhay-raj19/FitBody/assets/95575123/18e89509-f02a-4af9-8dac-56aa6ecde4a8)

**Comment by itz-mohit-014** [comment]
I am waiting for your reply, Please answer me ASAP @abhay-raj19
