### ISSUE TITLE
[BUG] Mobile View: Excessive Right Padding Overflow

### ISSUE THREAD

**Issue by Nishanth019** [abhay-raj19/FitBody#34]
**Issue Description:**

In the mobile view of the website, there is a significant amount of right padding, causing the page to scroll to the right. This misalignment impacts the user experience negatively.

**Video Attachment:**

https://github.com/abhay-raj19/FitBody/assets/122528380/a99ed0cc-4f4e-4621-8a9b-999e44a798e5

**Request for Assignment:**

I'd like to work on this issue and contribute a fix. Could you please assign this issue to me? Additionally, I'd like to tag this issue with "Hacktoberfest."

**Future Contributions:**

I'm enthusiastic about contributing more to this repository beyond this issue. I look forward to being an ongoing contributor and helping to improve the project.

**Comment by abhay-raj19** [comment]
Sure @Nishanth019 you can go for it.

**Comment by Nishanth019** [comment]
@abhay-raj19
