### ISSUE TITLE
text colour problem

### ISSUE THREAD

**Issue by dhairyagothi** [abhay-raj19/FitBody#362]
![image](https://github.com/abhay-raj19/FitBody/assets/142989448/335d91fa-4017-4711-a780-77c240ab6380)
some colour issues in dark mode . please assign me under gssoc24

**Comment by supriyajathar** [comment]
I want to work on this issue Assign me under GSSOC'24

**Comment by dhairyagothi** [comment]
@abhay-raj19 please assign to me with label gssoc
