### ISSUE TITLE
Bug 🐞: "Routing Navigation Errors" For The Pages 

### ISSUE THREAD

**Issue by MastanSayyad** [abhay-raj19/FitBody#366]
Hey, as I have developed the legal pages

![image](https://github.com/abhay-raj19/FitBody/assets/101971980/58327e67-26a1-44ee-853a-56899a61d6f9)

I was just checking my work After deployment and I found that The navigations to the pages don't work, after clicking it shows the following error

![image](https://github.com/abhay-raj19/FitBody/assets/101971980/ee8b8010-120a-40f1-bdbe-087ee86a02a6)

**It shows a 404 page.**

### **#Solution 1:**

- First, we will try by minor changing the path for the pages.

### **#Solution 2:**

After deploying the changed path if the error occurs again then based on my knowledge it only happens if you don't configure your `vercel.json` The routes don't get recognized except the "/" Home page routes. we have to:
-  Add a `vercel.json` file to the project.
- add these lines `{ "rewrites": [{ "source": "/(.*)", "destination": "/" }] }`
- On the vercel deployment dashboard ensure we pick vitejs as a framework 

@abhay-raj19 pls assign this issue to me under gssoc24.

**Comment by Sneha0019** [comment]
I have experience in this and can complete this issue ASAP. Please assign this me under GSSOC'24 with an appropriate label

**Comment by MastanSayyad** [comment]
Please assign this issue so that the pages routes work properly and do not show 404 page not found error @abhay-raj19
