### ISSUE TITLE
Mobile Navbar Not Closing in Mobile View

### ISSUE THREAD

**Issue by Nishanth019** [abhay-raj19/FitBody#37]
**Description**:
In mobile view, clicking on navbar sections (e.g., "Home" and "About") doesn't close the navbar as expected.

**Steps to Reproduce**:
Open the website in mobile view.
Click on any navbar section.
Navbar remains open

**Expected Behavior**:
The navbar should close after clicking a section for better user experience.

https://github.com/abhay-raj19/FitBody/assets/122528380/a129957a-fbbf-422e-b009-1b095bf760a1

Labels:
Assign me and assign the "Hacktoberfest, Hacktoberfest-accepted" label.
@abhay-raj19

**Comment by abhay-raj19** [comment]
@Nishanth019 go for it 👍.
