### ISSUE TITLE
Create a 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [abhay-raj19/FitBody#370]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/abhay-raj19/FitBody/assets/125277258/2bca46a4-e440-4543-8075-6a7360658d9e)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by anuragnegi000** [comment]
assign this issue to me
