### ISSUE TITLE
ADD Registration_form

### ISSUE THREAD

**Issue by Nikuunj** [abhay-raj19/FitBody#371]
### Describe the feature

**Type of Issue**
- [ ] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I would like to contribute to the Registration form.

@abhay-raj19 (Please assign me) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nikuunj** [comment]
@abhay-raj19

**Comment by Arifkhankhankhankhan** [comment]
Please assign me the issue of adding a registration form, under the GSSOC'24 label."
