### ISSUE TITLE
In dark theme the letters are in black colors.

### ISSUE THREAD

**Issue by mukilan2815** [abhay-raj19/FitBody#383]
**Describe the bug**
In dark theme the letters are black color which is not visible and i will add smooth scroll effect when user press navigation bar home schedule class... 

**To Reproduce**
1. Go to 'Website home page'
2. Click on 'Navbar Schedule'
3. See error

**Expected behavior**
Need to have smooth scroll effect for better experience 
**Screenshots**
![image](https://github.com/abhay-raj19/FitBody/assets/71129858/d4ff6070-ea69-48d2-836c-c8256c7d4868)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please assign this task under GSSOC'24

**Comment by Arifkhankhankhankhan** [comment]
I would like to work on fixing the black text visibility issue in the dark theme and adding a smooth scroll effect when the user clicks on the navigation bar (home, schedule, class, etc.). Can you assign this issue to me and add the GSSOC'24 label?
