### ISSUE TITLE
Nav Bar Color Changes

### ISSUE THREAD

**Issue by falgun143** [abhay-raj19/FitBody#389]
**Describe the bug**
When we scroll the nav bar we see variable color of the nav bar due to the behind images in the application and gives a bad user experience.

**To Reproduce**
Open the site and then scroll the navbar.

**Expected behavior**
Nav bar should have a single color while scrolling (keeping the color mode constant)
**Video**

https://github.com/abhay-raj19/FitBody/assets/105922142/bf743f2d-18a6-4ddd-9c47-9679160ee6f6

**Comment by falgun143** [comment]
@abhay-raj19 any thoughts on this?

**Comment by Arifkhankhankhankhan** [comment]
Could you please assign me the issue of changing the color of the navbar and tag it with the GSSOC'24 label?
