### ISSUE TITLE
FEAT: Adding a mail option in footer

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [abhay-raj19/FitBody#394]
**Is your feature request related to a problem? Please describe.**
Users find it frustrating and inconvenient to manually open their email client to compose a message.

**Describe the solution you'd like**
I propose adding a feature to the website that allows users to be redirected to their default email client when clicking on an email icon.

@abhay-raj19 please assign this issue to me under GSSoC'24

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
