### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by AkhilaSunesh** [abhay-raj19/FitBody#396]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/abhay-raj19/FitBody/assets/140897461/921ad2e6-f651-4bc9-b0c0-868144e9355a)

**Describe the solution you'd like**
Add a privacy policy page

What problem is this feature trying to solve?
Page not found error

How do we know when the feature is complete?
It will be reflected in the website

Kindly assign me this issue

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
