### ISSUE TITLE
Adding a Resgister and Signup page

### ISSUE THREAD

**Issue by Sujal7ss** [abhay-raj19/FitBody#398]
**Describe the solution you'd like**
Adding a Registration page to make the user authenticated and then only show the contents of the websites, like the videos and the diet plans.

What problem is this feature trying to solve?
Basin user authentication

How do we know when the feature is complete?
When user can create an account and use that account to access the resources

**Comment by Sneha0019** [comment]
Hey @abhay-raj19, I can add this feature with backend so that he can login again and his/her credentials are stored in database. I would like to contribute on this feature. Please assign it to me under an appropriate label
