### ISSUE TITLE
The footer element doesn't have any hover effect.

### ISSUE THREAD

**Issue by ASIMNEUPANE** [abhay-raj19/FitBody#4]
let me modify make change in the code

![footer](https://github.com/abhay-raj19/FitBody/assets/124865108/1aad111c-b478-4817-97af-5eecfa83adea)

**Comment by abhay-raj19** [comment]
Sure go for it ! @ASIMNEUPANE

**Comment by ASIMNEUPANE** [comment]
ok ill do it within a few day

**Comment by isaac-svg** [comment]
I an capable of adding doing this. Can you assign me to this?

**Comment by isaac-svg** [comment]
I an capable of adding doing this. Can you assign me to this?

**Comment by abhay-raj19** [comment]
Hey @isaac-svg good to see you here I have assigned this to @ASIMNEUPANE and if he/she fails then I will assign it to you ASAP.
