### ISSUE TITLE
Logo have invalid link $

### ISSUE THREAD

**Issue by Sujal7ss** [abhay-raj19/FitBody#401]
**Describe the bug**
A logo should be used to navigate to the homepage, but it is giving error

**To Reproduce**
1. Go to homepage
2. Click on Logo

**Expected behavior**
navigate to the homepage

 
![Screenshot 2024-06-04 174228](https://github.com/abhay-raj19/FitBody/assets/104003078/3873670f-76c3-4d44-a234-73cb6307b096)

![Screenshot 2024-06-04 174246](https://github.com/abhay-raj19/FitBody/assets/104003078/de45ca3d-f377-42a4-98df-27d74d35136c)

**Comment by Sneha0019** [comment]
I can work on this issue. Please assign it to me under an appropriate label for GSSOC'24!
