### ISSUE TITLE
[Bug] Navbar buttons not navigating

### ISSUE THREAD

**Issue by Chetan8299** [abhay-raj19/FitBody#403]
**Describe the bug**
The Navbar buttons do not have proper routing applied

**To Reproduce**
1. Go to the website
2. Click on either get started button or free diet button 
3. After that we cannot navigate to home page

**Expected behavior**
After clicking on the Home button the user should be navigated to the homepage

**Screenshots**
![image](https://github.com/abhay-raj19/FitBody/assets/167693543/2795072d-5e3b-416b-8341-a63f1e0fc105)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 125.0.6422.142

**Smartphone (please complete the following information):**

**Additional context**
There should be proper pages for other options too with proper routing

**Comment by Arifkhankhankhankhan** [comment]
I would like to work on this issue. Can you assign it to me and add the GSSOC'24 label?
