### ISSUE TITLE
Spelling Error on the Exercises Page

### ISSUE THREAD

**Issue by navyabijoy** [abhay-raj19/FitBody#407]
**Describe the bug**
There is a spelling error in the Exercises.jsx file. 'benifits' should be changed to 'benefits'

**Screenshots**
this: 
![GPfaH-AaYAAT_ko](https://github.com/abhay-raj19/FitBody/assets/115248350/e3fbd013-47d3-425e-8312-ac0e1496a502)
should be changed to this: 
![GPfaME6aAAAY8F4](https://github.com/abhay-raj19/FitBody/assets/115248350/7604acf2-2ede-4f6d-9cdb-08f42fcf5dde)

- Please assign me this issue
-Also label the issue as gssoc
Thank you.

**Comment by Pavitra2128** [comment]
i would like to edit in the Exercises.jsx file. 'benifits' should be changed to 'benefits'
