### ISSUE TITLE
Logo redirecting to Unexpected Page 

### ISSUE THREAD

**Issue by sarthakmisal** [abhay-raj19/FitBody#410]
**Describe the bug**
When clicked on the logo named FitBody in Navbar of Home Page or any page it redirects to unexpected Page

**To Reproduce**
1. Go to 'Home Page(any)'
2. Click on **FitBody** named Logo in Navbar'
3. See Error

**Expected behavior**
It should redirect to its home page

**Screenshots**
on clicking this button
![image](https://github.com/abhay-raj19/FitBody/assets/142015424/cf4f0add-9886-459c-976a-4f81db7d079c)
This is the output
![image](https://github.com/abhay-raj19/FitBody/assets/142015424/755cd095-691a-4886-88ba-fd993532ca3f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by RawAtCode** [comment]
@abhay-raj19 can you assign me this issue??

**Comment by RahulNaha** [comment]
@abhay-raj19 Willing to work .Please assign this issue to me
