### ISSUE TITLE
Registration feature not Enabled

### ISSUE THREAD

**Issue by sarthakmisal** [abhay-raj19/FitBody#413]
Registration feature for users is not enabled neither Login
I suggest to add registration and Login for users and when Purchasing the Plan registration is must 
As I have included that Purchase -> Payment Gateway issue in #411 

**Record**
 I have read the Contributing Guidelines
 I have starred the repository

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
