### ISSUE TITLE
Proper Authentication System.

### ISSUE THREAD

**Issue by PriyanshuValiya** [abhay-raj19/FitBody#414]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Show User's name in main slide to give personal experience to user.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
Giving Proper Authentication to website.

How do we know when the feature is complete?
Less than 1 week after assigning.

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
