### ISSUE TITLE
Adding Registration and login pages and Display a form to fill when clicked on join now and and applications are displayed to admin of gym

### ISSUE THREAD

**Issue by shanmukhi90** [abhay-raj19/FitBody#415]
I would like to add Register and login pages and when user clicks on join Now they are asked to login and then taken to application form consisting their details and the timings they wish to come gym etc and all those applications should be visible to admin if there is any vacant seats in that time slots admin can contact them via details given by user.

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
