### ISSUE TITLE
Floating animation to the home image.

### ISSUE THREAD

**Issue by Damini2004** [abhay-raj19/FitBody#416]
**Is your feature request related to a problem? Please describe.**
The current home image on the website is static, making the landing page appear less dynamic and engaging. This can result in a less captivating first impression for visitors, potentially impacting the overall user experience and engagement.

**Describe the solution you'd like**
Implement a subtle floating animation to the home image. This animation should gently move the image up and down (or in a slow, circular motion) to create a sense of depth and liveliness. The animation should be smooth and not too distracting, maintaining the focus on the content while enhancing visual appeal.

**Describe alternatives you've considered**
Parallax Scrolling Effect: Create a parallax scrolling effect where the home image moves at a different speed than the rest of the page content as the user scrolls.
Hover Animation: Animate the home image only when the user hovers over it, providing interactive feedback.
Fade In/Out Animation: Use a fade-in and fade-out effect to bring attention to the home image without constant movement.
No Animation: Keep the home image static to avoid any potential distraction for users who prefer minimal movement on the page.

**Additional context**
![image](https://github.com/abhay-raj19/FitBody/assets/119414762/4efef02a-97c4-498b-8acc-87394564d6a0)
https://search.app.goo.gl/LEypFHF
What problem is this feature trying to solve?
This feature aims to:

Enhance the visual appeal of the landing page.
Create a more dynamic and engaging first impression for visitors.
Potentially increase user interaction and time spent on the page.

How do we know when the feature is complete?
As i create the pull request.

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
