### ISSUE TITLE
Register button not working

### ISSUE THREAD

**Issue by PrachiJadhav2310** [abhay-raj19/FitBody#417]
The register button in navbar is not working .

**Comment by Shubham-Zone** [comment]
@abhay-raj19 please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by PrachiJadhav2310** [comment]
@abhay-raj19 Please assign this issue to me as  i have opened it and have started working on it

**Comment by bhatiatanish225** [comment]
@abhay-raj19 pls assign this issue to me
