### ISSUE TITLE
Want to Fix Dark mode text-vviblity issue

### ISSUE THREAD

**Issue by nishant0708** [abhay-raj19/FitBody#423]
**Describe the bug**

**To Reproduce**
1. Go to 'dark mode'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24 @abhay-raj19 .
