### ISSUE TITLE
Spelling Error in Homepage

### ISSUE THREAD

**Issue by aanchalpahuja18** [abhay-raj19/FitBody#424]
**Describe the bug**
Spelling Error is there in Homepage 

**Expected behavior**
Benefits should be there instead of Benifits 

**Screenshots**
![image](https://github.com/abhay-raj19/FitBody/assets/136963878/f7dd4779-d7da-4071-a5d3-ebc6b4d6bd43)

**Comment by aanchalpahuja18** [comment]
@abhay-raj19 Kindly assign this issue to me I will go through all the grammatical errors & spelling mistakes and submit it to you really quick

**Comment by Ayushi-Choudhary22** [comment]
I’ve carefully reviewed the details of this issue and believe

**Comment by Ayushi-Choudhary22** [comment]
Hello @abhay-raj19 !  please assign me this issue.
