### ISSUE TITLE
Hamburger icon needs to be replaced with close icon if menu opens 

### ISSUE THREAD

**Issue by kapilG0** [abhay-raj19/FitBody#438]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240626_000418](https://github.com/abhay-raj19/FitBody/assets/59639410/646e6221-ee6b-4571-bc94-64a51603931d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @abhay-raj19 please assign this issue to me under gssoc 24

**Comment by RawAtCode** [comment]
hey! can you assign me this issue?
