### ISSUE TITLE
Add About Us and Support Pages

### ISSUE THREAD

**Issue by r7projects-shayan** [abhay-raj19/FitBody#439]
**Is your feature request related to a problem? Please describe.**

There is currently no About Us and Support Pages

**Describe the solution you'd like**

Proper about us and support pages fully responsive for all devices and dimensions

How do we know when the feature is complete?

The pull request will be mentioned

Screenshots

![Screenshot 2024-06-30 004430](https://github.com/abhay-raj19/FitBody/assets/167475552/6e6c3cea-d680-4b30-aadb-4970ebd89499)

**Comment by r7projects-shayan** [comment]
@abhay-raj19 Kindly assign me this issue so that I can work on it

**Comment by RahulNaha** [comment]
@abhay-raj19 Willing to work .Please assign this issue to me
