### ISSUE TITLE
Adding a register page for register button

### ISSUE THREAD

**Issue by shraddhha** [abhay-raj19/FitBody#447]
**Is your feature request related to a problem? Please describe.**
Creating a register page for the users to register when they click on register button.

**Describe the solution you'd like**
Creating a register page for the users to register when they click on register button.

**Describe alternatives you've considered**

**Additional context**

![register](https://github.com/abhay-raj19/FitBody/assets/125660723/f60c0faf-ef25-4bf7-bf33-ce1a91651a45)

What problem is this feature trying to solve?
Allowing users to register themselves.

How do we know when the feature is complete?
The register button on clicking will open a register page.

**Comment by samr874** [comment]
@shraddhha what is the staus of this issue ?? are the contributions still active?

**Comment by shraddhha** [comment]
Yes ,I am actively working on this issue and will submit a pull request by tomorrow.

**Comment by samr874** [comment]
@shraddhha Can someone tag the maintainer or head of the project

**Comment by samr874** [comment]
@shraddhha I think we need to look after redesigning the UI?
