### ISSUE TITLE
Make navbar sticky on top

### ISSUE THREAD

**Issue by Iamdivyak** [abhay-raj19/FitBody#50]
Kindly assign under hacktoberfest

**Comment by Iamdivyak** [comment]
Hey @abhay-raj19. I tried to make the navbar sticky in mobile view. but it seems like the code is written to make the navbar sticky not it's not working. I changed, removed, and added many possibilities but still did not succeed. Can you help?!!

**Comment by Pritam-2002** [comment]
can i work on this issue?

**Comment by abhay-raj19** [comment]
@Pritam-2002 go for it .
