### ISSUE TITLE
Addressing Hover Spacing Issue in Website Header.

### ISSUE THREAD

**Issue by pranshu-5123** [abhay-raj19/FitBody#57]
![ewt](https://github.com/abhay-raj19/FitBody/assets/112655759/cd51e85c-9a9d-4af8-9e6b-d7bd96c747e6)
I have noticed an issue with extra spacing when hovering over the 'Contact Us' section in the website's header. I kindly request to be assigned to this issue, as I am confident I can resolve it effectively.

**Comment by abhay-raj19** [comment]
Hey @pranshu-5123 do make a git pull ,i am not facing any  such issue
Pls do check the latest deployment.
