### ISSUE TITLE
Fix Non-Cyclic Behavior of SwiperComponent.

### ISSUE THREAD

**Issue by pranshu-5123** [abhay-raj19/FitBody#58]
The Swiper component on the website lacks cyclic behavior, preventing seamless slide navigation. The issue requires resolving this limitation for improved user experience.
Assign me this Issue,I can resolve it...

**Comment by abhay-raj19** [comment]
Go for it @pranshu-5123 and raise the PR ASAP.

**Comment by Piyush07p** [comment]
can you assign it to me
