### ISSUE TITLE
Render to landing page while clicking the logo/FitBody

### ISSUE THREAD

**Issue by ASIMNEUPANE** [abhay-raj19/FitBody#6]
It will be great experience for the user if he/she can click on the logo or FitBody and page can rerender to the main landing page.
let  add this feature for your website

![image](https://github.com/abhay-raj19/FitBody/assets/124865108/f162a671-e2b4-46b0-9940-90feb99cebbb)

**Comment by abhay-raj19** [comment]
Sure for that and also add a functionality to navigate to the top .

Can you add it?? @ASIMNEUPANE

**Comment by ASIMNEUPANE** [comment]
okay sure , I can do that

**Comment by Noazs** [comment]
Hello, i would like to take this issue.

**Comment by abhay-raj19** [comment]
Hey @Noazs good to see you here !!
you can check the issue #5 and #7 if you like to contribute to them .

or else you can open a new issue here .

go check it out!!

**Comment by abhay-raj19** [comment]
👋 @ASIMNEUPANE go for it 
and raise up PR ASAP.

**Comment by ASIMNEUPANE** [comment]
> 👋 @ASIMNEUPANE go for it and raise up PR ASAP.

yeah don't worry I have almost finish that . I will raise pr tomorrow  sure.

**Comment by ASIMNEUPANE** [comment]
I have solved all the problems and sent a PR request. Please check that PR
request and let me know if you want some other changes in the code.
