### ISSUE TITLE
Resolving Design Issue of Dark Mode Button

### ISSUE THREAD

**Issue by kartik2433** [abhay-raj19/FitBody#66]
@abhay-raj19  There Is Little Design Issue In Light/Dark Mode Toggle Button. Dark Mode Moon Is Little Bit Visible In Light Mode. Can You Assign This Issue To me.

![image](https://github.com/abhay-raj19/FitBody/assets/95977507/2578f9c2-8702-4cf0-a9f0-b0de4dc1ad4f)

**Proposed Solution**

![image](https://github.com/abhay-raj19/FitBody/assets/95977507/304cd102-9cda-4b98-9d11-ab0a2067766d)

**Comment by abhay-raj19** [comment]
Go up for the changes @kartik2433
