### ISSUE TITLE
[Feature to be added] Light/Dark Mode

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#7]
A feature is to be added like that of full dark mode and light mode 

` a side nav button for toggling to light and dark`

Button Position: Right side,

Example:
<img width="203" alt="image" src="https://github.com/abhay-raj19/FitBody/assets/96302417/aec40335-51f8-42ee-b451-31d0030c8d89">

Toggling button similar to this without Text inside the button.

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thank you.

**Comment by abhay-raj19** [comment]
Go for it now @Atulsoam562003

**Comment by Nishanth019** [comment]
I think Dark/Light mode is not done still. Please assign this to me. I made it already. I will raise the PR. @abhay-raj19

**Comment by abhay-raj19** [comment]
Its not been added @Nishanth019 .
You can work on it now also

**Comment by Nishanth019** [comment]
I sent a pull request. Label this issue as hactoberfest-accepted sir. So that it may include in hactoberfest pull requests @abhay-raj19

**Comment by Nishanth019** [comment]
@abhay-raj19

**Comment by abhay-raj19** [comment]
good contribution @Nishanth019 💙

**Comment by Nishanth019** [comment]
Merge it sir. Label this PR as hactoberfest-accepted sir. So that it may include in hactoberfest pull requests. I will make more contributions. I want to complete hactoberfest 4 PRs successfully. @abhay-raj19
