### ISSUE TITLE
[BUG] Home hover layout

### ISSUE THREAD

**Issue by icepick4** [abhay-raj19/FitBody#81]
Hello,

I find out that when you hover the home link in the header, it doesnt fit in the box and overflow, see :

No hover : 

![image](https://github.com/abhay-raj19/FitBody/assets/82316285/cfbbda16-504c-467b-9f21-d3e8a7bc90f6)

With hover : 

![image](https://github.com/abhay-raj19/FitBody/assets/82316285/ded8fa0b-cad3-4fd4-af84-faa8e0f4c467)

**Comment by icepick4** [comment]
I can fix it, you can assign it to me

**Comment by abhay-raj19** [comment]
@icepick4 go for it .
