### ISSUE TITLE
Contact Us Styling

### ISSUE THREAD

**Issue by prasanna1225** [abhay-raj19/FitBody#84]
I want to change the styling of contact us box .
![Screenshot (34)](https://github.com/abhay-raj19/FitBody/assets/94883909/d064d67b-94f9-4c6e-aa25-b9f72f8ee4ee)
so assign me that issue

**Comment by parth3083** [comment]
Hey, I am a frontend developer who creates stunning and modern websites.
I completed the internship as a frontend developer.
I create websites with HTML, CSS, JS, and React, and I use JS libraries for animation and smooth scrolling.
The following are the works where I used lgsap animation and locomotive js : 
https://exoape-clone-parth.netlify.app/
https://ochi-clone-parth.netlify.app/

**Comment by rawani123** [comment]
can you assign this issue to me ?from (GSSOC'24)

**Comment by Nikhilsaini481-tech** [comment]
Hii , My name is Nikhil saini and  i am a full stack developer . I can resolve your issue can you assign this issue to me 
(GSSOC'24)

**Comment by Varsani2520** [comment]
Hi, can you assign this issue to me ? and also add the label for this issue ,i already make a lots of e-commerce website so ,i have a good skill for this issues...

**Comment by RakshitaJain2126** [comment]
Could you assign this issue to me as well? I have experience in this and I can do it better.
