### ISSUE TITLE
Creating the Register Page for the website

### ISSUE THREAD

**Issue by nitin-pandita** [abhay-raj19/FitBody#85]
I will help in creating the register page for the website

**Comment by abhay-raj19** [comment]
Sure!! You  can Proceed 🙂.

**Comment by nitin-pandita** [comment]
@abhay-raj19 thank you

**Comment by GuptaKap** [comment]
I'm capable of creating a register page. Please assign me to the task

**Comment by nitin-pandita** [comment]
@GuptaKap actually i am working on this project

**Comment by Ayushhgupta39** [comment]
@nitin-pandita Any updates?

**Comment by abhay-raj19** [comment]
@nitin-pandita Due to no further updates we are closing up the issue.
