### ISSUE TITLE
 Creating  Backend file Using MVC pattern 

### ISSUE THREAD

**Issue by Crazzy-novus** [abhay-raj19/FitBody#86]
I am interested in this project. I can structure a backend using Node.js, express and MongoDB. I thinks **_MVC pattern**_ fits best for this "FitBody" application. and I can integrate **JWT token for authentication** which make the webpage more secure. Please assign this Issue to me.

**Comment by abhay-raj19** [comment]
Ohh that's looks good issue will be assigning soon you can go ahead !!!
