### ISSUE TITLE
[ High Priority ]Convert to Vite Bundler

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#87]
Make vite integrations and do move this whole project into vite bundler.

why to move ?

-> As while initilising it on a AWS EC2 instance it takes up a lot of resources .
-> Not able to run on a VM instance on Azure .

Ref :
https://vitejs.dev/guide/
https://vitejs.dev/

**Comment by rahulpoonia29** [comment]
@abhay-raj19 I would like to work on this issue. Could you assign the issue under GSsoC

**Comment by Shobhit-Nagpal** [comment]
hey, would love to work on this under gssoc' 24 :)

**Comment by Shobhit-Nagpal** [comment]
hey @abhay-raj19, could you assign this issue under my name since the pr is now merged. gssoc won't count the contribution otherwise.

thanks in advance :)
