### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#89]

**Comment by Puskar-Roy** [comment]
hey @abhay-raj19 I am interested in this project. I can add a docker file, can you please assign me.

**Comment by abhay-raj19** [comment]
proceed @Puskar-Roy

**Comment by SumitKumar-17** [comment]
@abhay-raj19 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by Puskar-Roy** [comment]
@abhay-raj19 I'm working on it

**Comment by Chelseasingla1** [comment]
Hi i have worked on docker before if there would be something still left then please assign this issue to me under GSSoC'24

**Comment by MishraTanishq619** [comment]
I can add Docker as well as Docker-compose file,
that also for both development and production environments specefically.

I would like to do this ..
Please assign me for gssoc.

**Comment by Ayushhgupta39** [comment]
@Puskar-Roy Are you still working on it?

**Comment by MishraTanishq619** [comment]
Assign me please for gssoc.

**Comment by MishraTanishq619** [comment]
I will be Giving a Proper PR tomorrow.

**Comment by MishraTanishq619** [comment]
I there any Problem in PR #277 
I Eager to know why it is closed, unmerged.

**Comment by Ayushhgupta39** [comment]
> I there any Problem in PR #277 I Eager to know why it is closed, unmerged.

The changes in the package.json may result in deployment errors. Please try to take latest code from the main branch and then raise a new PR
