### ISSUE TITLE
Price button hover cuts-off issues

### ISSUE THREAD

**Issue by Ayush-may** [abhay-raj19/FitBody#90]
Issue :
when I'm hovering over the price card button the animation works well but when I remove the mouse the animation cuts of fast.

[Screencast from 09-05-24 07:49:48 PM IST.webm](https://github.com/abhay-raj19/FitBody/assets/112775332/2e83658e-3d42-41e1-b26b-4f7c0fc3ec15)

**Comment by Ayush-may** [comment]
assign this issue to me , i can fix this

**Comment by abhay-raj19** [comment]
Sure! Now you can proceed!!

**Comment by Ayush-may** [comment]
@abhay-raj19 pls add the level tag in this issue , gssoc members are saying it is mandatory to have both gssoc and level tag 
thank u
