### ISSUE TITLE
Navbar not shown

### ISSUE THREAD

**Issue by rahulpoonia29** [abhay-raj19/FitBody#91]
The navbar is not shown initially when the theme is changed.
Scroll is needed to make it appear.

![Screenshot 2024-05-09 210339](https://github.com/abhay-raj19/FitBody/assets/140232466/5011ad02-2797-42d6-bb27-47323415acd6)

**Comment by rahulpoonia29** [comment]
@abhay-raj19  Can you assign the issue under GSSoC'24

**Comment by abhay-raj19** [comment]
@rahulpoonia29 Now you can work on this !!

**Comment by rawani123** [comment]
can you assign this to me also?

**Comment by abhay-raj19** [comment]
it is showing prior to your PR

![image](https://github.com/abhay-raj19/FitBody/assets/96302417/a5c8b06b-bc4c-4c26-b934-c0be3163af36)


it was there and working fine .

**Comment by rahulpoonia29** [comment]
@abhay-raj19 The navbar is not shown for the start when theme is changed. You need to scroll to make it appear.

**Comment by abhay-raj19** [comment]
are you saying to fix it at scroll time also ?

**Comment by rahulpoonia29** [comment]
Scroll down to more than 80vh and then change the theme. The navbar would not be visible. Then if you scroll it would become visible again. I have fixed that issue.

**Comment by abhay-raj19** [comment]
Okay Got it . @rahulpoonia29 
Thanks For contributing 💙.
