### ISSUE TITLE
Making the navbar and testimonials dark mode compatible

### ISSUE THREAD

**Issue by rahulpoonia29** [abhay-raj19/FitBody#92]
![Screenshot 2024-05-09 210244](https://github.com/abhay-raj19/FitBody/assets/140232466/cb9751f0-4ece-4b74-bec9-114731f2a40c)
![Screenshot 2024-05-09 211311](https://github.com/abhay-raj19/FitBody/assets/140232466/20bf007d-11cb-4573-bdd7-64d1c5a50e75)

**Comment by rahulpoonia29** [comment]
@abhay-raj19 Can you assign the issue under GSSoC'24

**Comment by Manaswini123456** [comment]
Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue  so that I can provide my insights and solutions.

**Comment by abhay-raj19** [comment]
> Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue so that I can provide my insights and solutions.

This issue have been completed @Manaswini123456 you can think of a new one 🙂.

**Comment by abhay-raj19** [comment]
Will be happy to assign You @Manaswini123456
