### ISSUE TITLE
Init Tailwind remove vanilla CSS

### ISSUE THREAD

**Issue by abhay-raj19** [abhay-raj19/FitBody#93]

**Comment by rahulpoonia29** [comment]
@abhay-raj19 As I am working on the navbar bug and dark mode completion, I could initialise the Tailwind CSS and complete the work in Tailwind.

**Comment by mdrehan369** [comment]
I can initialize tailwind. Please assign this issue to me

**Comment by abhay-raj19** [comment]
move to vite first then tailwind it would be great else would fail up the deployment life cycles

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
