### ISSUE TITLE
Create Login Page with forgot password having OTP authentication

### ISSUE THREAD

**Issue by Ankesh2004** [abhay-raj19/FitBody#95]
I can create Login Page with functionality of forgot password which can be recovered via OTP authentication.
Kindly assign me this issue under GSSOC'24.

**Comment by ShoveetSingh** [comment]
Hey mate. Shoveet here.
I can create login page with any desired functionality using modern web technologies.
I am a gssoc contributor and have experience of 1.5 years.
Kindly assign this to me.

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project as a part of GSSOC 2024. I am a MERN stack developer and I have worked on several projects and won hackathons as well. I can create login page with forgot password having OTP authentication. 

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by abhay-raj19** [comment]
@ShoveetSingh @nakshatravyas glad to see you profiles and handles .
as @Ankesh2004 has opened up the issue I will be giving the first preference to him .
you all can look into some issues that are created up by me and proceed there .

and Would be great if you open up the new issues though.

**Comment by abhay-raj19** [comment]
if @Ankesh2004 fails to do so then I can assign it to next contributor.

**Comment by sahithi000** [comment]
Hey I'm GSSOC contributor can u please assign this task for me

**Comment by mohdjami** [comment]
Hi @abhay-raj19 , It's been 5 days there is no update regarding the issue and neither any PR is raised. Assign this issue to me so that I can start working on it under GSSOC'24 level 3. 

I will be using jwt for authorisation.

**Comment by Ayushhgupta39** [comment]
@Ankesh2004 Are you still working on this?

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by abhay-raj19** [comment]
> @Ankesh2004 Are you still working on this?

@Ankesh2004 Closing it up Due to no Response to the issue.

**Comment by abhay-raj19** [comment]
> I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
