### ISSUE TITLE
[ENHANCEMENT] Dark Mode For Card Elements

### ISSUE THREAD

**Issue by chaitanyarora** [abhay-raj19/FitBody#96]

**Comment by chaitanyarora** [comment]
Will implement dark mode even on card elements that are missed out when dark mode is applied.

**Comment by abhay-raj19** [comment]
Not just change up the color it would be cool if you come up with new UI that looks cool in dark mode retaining the card format.

**Comment by chaitanyarora** [comment]
Sure sir, on it!

**Comment by chaitanyarora** [comment]
#189

**Comment by chaitanyarora** [comment]
@abhay-raj19 sir any updates?
