### ISSUE TITLE
Adding google authentication in the project

### ISSUE THREAD

**Issue by Vishnu1804K** [abhay-raj19/FitBody#97]
I want to add google authentication into your project so that it will be easy for the users to do goggle login and signup . please assign me this issue under GSSOC'24

**Comment by Ayush-may** [comment]
how u gonna do this ?
u need to create firebase file and then how will u going to manage all that secret keys ?
I just want to know @Vishnu1804K

**Comment by Vishnu1804K** [comment]
Using passport js I can built the google authentication

**Comment by Ayush-may** [comment]
never heard about this , gotta check that 
thanks buddy this info will help me too in my future projects !

**Comment by Vishnu1804K** [comment]
hey @parth3083  it is my issue you raise your own issue

**Comment by abhay-raj19** [comment]
@Ayush-may we can manage those secrets if we follow the deployment secrets under the GitHub secrets , and can be used by the user if we create dev secrets that we should opensource to everyone for testing the application out.

**Comment by abhay-raj19** [comment]
> Hey, I am a MERN developer who creates stunning and modern websites. I completed the internship as a frontend developer. I create websites with HTML, CSS, JS, and React, and I use JS libraries for animation and smooth scrolling. I can add an authentication feature that uses Google OAuth.

Sure you can open up the new issue for that.
