### ISSUE TITLE
Adding APIs for login and signup

### ISSUE THREAD

**Issue by mehtakevan** [abhay-raj19/FitBody#98]
Creating the apis for login and signup functionality

**Comment by mehtakevan** [comment]
@abhay-raj19 can you please assign this issue to me under gssoc24

**Comment by ShoveetSingh** [comment]
@abhay-raj19 Can you assign the project to me .
I have good experience working with web technologies.
I can add API as well.

**Comment by mdrehan369** [comment]
@abhay-raj19 Sir please assign this issue to me. I had already created this kind of APIs in my past projects

**Comment by GuptaKap** [comment]
I've already worked on a MERN project. Please consider assigning me under gssoc."

**Comment by GuptaKap** [comment]
I can easily integrate login and signup APIs. Please assign me to handle this task

**Comment by IP80808080** [comment]
@abhay-raj19 Sir please assign this issue to me. Also Sir can you plz label it for level

**Comment by abhay-raj19** [comment]
issue is been created up by @mehtakevan if he fails to submit up the PR then will assign to the next
