### ISSUE TITLE
Improve Sidebar Appearance to Match Website Theme

### ISSUE THREAD

**Issue by dhruv389** [abhay-raj19/FitBody#99]
---
**Description:**
The current background color, font color, and icon of the sidebar are not aligned with the website's theme, resulting in an inconsistent visual presentation. To enhance the overall aesthetics and user experience, I propose making the following changes:

Adjusting the background color to match the website's theme.
Updating the font color for better readability and visual harmony.
Changing the sidebar icon to better represent its function and improve visual appeal.

Proposed Changes:

Change background color.
Update font color .
Replace sidebar icon  .

**Now ,It Looks :**

![Screenshot 2024-05-10 114456](https://github.com/abhay-raj19/FitBody/assets/117587892/fac9ace3-da14-4f77-8ea1-249888bdc5df)

**After Changes :**

![Screenshot 2024-05-10 120240](https://github.com/abhay-raj19/FitBody/assets/117587892/4f613631-0120-4b03-8efb-05cb0b33acbe)

---
Please assign me this Issue under Gssoc'24.
---

**Comment by ShashankMPatil** [comment]
@abhay-raj19 Can you assign the issue under GSSoC'24

**Comment by mdrehan369** [comment]
I can fix this. Please assign this issue to me

**Comment by mdrehan369** [comment]
under GSSOC 2024

**Comment by abhay-raj19** [comment]
@dhruv389 remove sharpness from the sidebar icon make it bit curvy and also enhance the color you stated up .

**Comment by Aadityagoel15** [comment]
Hey @abhay-raj19 
Can you please assign this issue to me under GSSOC 2024
